### ISSUE TITLE
Change "litf" to "form"

### ISSUE THREAD

**Issue by JMdictProject** [JMdictProject/JMdictIssues#1]
Robin asked in January 2020:
If it's not too much of a hassle, can I suggest changing the literary/formal tag to [form] (or something similar)? 
I just feel that [litf] looks a little too similar to [lit] and isn't as easy to remember or recognise. Also, "formal" probably best describes the words it will be used for.

**Comment by JMdictProject** [comment]
Fair enough. I'll add this to the next batch of tag changes. Perhaps [formal]?

**Comment by jimmubreen** [comment]
Just testing if I can comment from my usual account.
Here is a link to the 焼亡  entry which uses"litf": https://www.edrdg.org/jmdictdb/cgi-bin/entr.py?svc=jmdict&sid=&q=2842957

**Comment by JMdictProject** [comment]
This has now been changed.
