### ISSUE TITLE
[rK] kanji forms with high priority tags

### ISSUE THREAD

**Issue by stephenmk** [JMdictProject/JMdictIssues#100]
We currently have 13 kanji forms that have a rare kanji [rK] tag along with a high priority tag (ichi1, spec1, etc.).

I believe the current policy is to avoid using these tags together. Can an editor please remove the priority tags?

sequence | kanji form | reading
-- | -- | --
1002530 | お凸 | おでこ
1007500 | だらし無い | だらしない
1008050 | 序でに | ついでに
1189360 | 何方 | どちら
1205800 | 確乎 | かっこ
1315740 | 持て成す | もてなす
1403050 | 騒めく | ざわめく
1410760 | 態と | わざと
1449890 | 到頭 | とうとう
1525680 | 迄 | まで
1569000 | 焜炉 | こんろ
1591290 | 切っ掛け | きっかけ
1591900 | 奇麗 | きれい

**Comment by robinjmdict** [comment]
That's right, they should be removed. I'll do it. Thanks for the list.

**Comment by JMdictProject** [comment]
> I believe the current policy is to avoid using these tags together. 

It's more an anomaly that dates back to the earlier days of the project. In the maintenance system that was used before the current database was introduced in 2010 a tag like [ichi1] had to be on both a kanji form and a reading for it to be tagged as high-frequency. Thus the 
何方/どちら entry had both forms tagged, although the IchiMan source doesn't have the kanji form.
Our current system doesn't have that restriction, and the EDICT format used by WWWJDIC, etc, has a (P) tag even if only a reading has the [ichi1], [spec1], etc. tags. See the もたらす(#1573190) entry as an example.
There's certainly no problem with removing priority tags from kanji forms with [rK] or [sK] tags.

**Comment by JMdictProject** [comment]
I think this can close.
