### ISSUE TITLE
Messy headword sections that can be tidied with [sK] tags

### ISSUE THREAD

**Issue by stephenmk** [JMdictProject/JMdictIssues#102]
I've been working on a distribution of JMdict that organizes the kanji forms from entries with multiple readings into a table.

When there are many long forms in an entry, this table flies off the screen.

<details>
  <summary>Example: entry for 捕らぬ狸の皮算用</summary>

![hatch](https://github.com/JMdictProject/JMdictIssues/assets/8003332/00056ff4-fd86-4145-8a8c-6aecf7c08802)
</details>

Since we're no longer enforcing reading restrictions due to hiragana/katakana differences, and since we now have search-only tags that we can use, all of these entries can be drastically simplified. I think this will be helpful to all apps which use JMdict data.

As a simple criteria for finding these sorts of entries, I looked at the sum of characters in the top header row of my tables. Below is a list of entries where the sum was greater than 30. I thought I'd share it here in case JMdict editors would like to help work through them.

sequence | character count sum
-- | --
[2074250](https://www.edrdg.org/jmwsgi/entr.py?svc=jmdict&sid=&q=2074250) | 34
[2589380](https://www.edrdg.org/jmwsgi/entr.py?svc=jmdict&sid=&q=2589380) | 34
[2690580](https://www.edrdg.org/jmwsgi/entr.py?svc=jmdict&sid=&q=2690580) | 34
[2170750](https://www.edrdg.org/jmwsgi/entr.py?svc=jmdict&sid=&q=2170750) | 33
[2791100](https://www.edrdg.org/jmwsgi/entr.py?svc=jmdict&sid=&q=2791100) | 33
[2841834](https://www.edrdg.org/jmwsgi/entr.py?svc=jmdict&sid=&q=2841834) | 33
[1777600](https://www.edrdg.org/jmwsgi/entr.py?svc=jmdict&sid=&q=1777600) | 32

### Reviewed Entries

sequence | character count sum
-- | --
[~2102990~](https://www.edrdg.org/jmwsgi/entr.py?svc=jmdict&sid=&q=2102990) | 86
[~1514120~](https://www.edrdg.org/jmwsgi/entr.py?svc=jmdict&sid=&q=1514120) | 72
[~2836087~](https://www.edrdg.org/jmwsgi/entr.py?svc=jmdict&sid=&q=2836087) | 65
[~1608470~](https://www.edrdg.org/jmwsgi/entr.py?svc=jmdict&sid=&q=1608470) | 58
[~2784340~](https://www.edrdg.org/jmwsgi/entr.py?svc=jmdict&sid=&q=2784340) | 57
[~1589980~](https://www.edrdg.org/jmwsgi/entr.py?svc=jmdict&sid=&q=1589980) | 50
[~1603480~](https://www.edrdg.org/jmwsgi/entr.py?svc=jmdict&sid=&q=1603480) | 50
[~2159000~](https://www.edrdg.org/jmwsgi/entr.py?svc=jmdict&sid=&q=2159000) | 50
[~2836339~](https://www.edrdg.org/jmwsgi/entr.py?svc=jmdict&sid=&q=2836339) | 50
[~2237240~](https://www.edrdg.org/jmwsgi/entr.py?svc=jmdict&sid=&q=2237240) | 49
[~1595900~](https://www.edrdg.org/jmwsgi/entr.py?svc=jmdict&sid=&q=1595900) | 48
[~2684060~](https://www.edrdg.org/jmwsgi/entr.py?svc=jmdict&sid=&q=2684060) | 48
[~1961830~](https://www.edrdg.org/jmwsgi/entr.py?svc=jmdict&sid=&q=1961830) | 48
[~2850246~](https://www.edrdg.org/jmwsgi/entr.py?svc=jmdict&sid=&q=2850246) | 46
[~2417440~](https://www.edrdg.org/jmwsgi/entr.py?svc=jmdict&sid=&q=2417440) | 44
[~2714130~](https://www.edrdg.org/jmwsgi/entr.py?svc=jmdict&sid=&q=2714130) | 44
[~1855790~](https://www.edrdg.org/jmwsgi/entr.py?svc=jmdict&sid=&q=1855790) | 42
[~2373400~](https://www.edrdg.org/jmwsgi/entr.py?svc=jmdict&sid=&q=2373400) | 42
[~2850280~](https://www.edrdg.org/jmwsgi/entr.py?svc=jmdict&sid=&q=2850280) | 42
[~2251580~](https://www.edrdg.org/jmwsgi/entr.py?svc=jmdict&sid=&q=2251580) | 41
[~1850370~](https://www.edrdg.org/jmwsgi/entr.py?svc=jmdict&sid=&q=1850370) | 39
[~2064850~](https://www.edrdg.org/jmwsgi/entr.py?svc=jmdict&sid=&q=2064850) | 39
[~2018320~](https://www.edrdg.org/jmwsgi/entr.py?svc=jmdict&sid=&q=2018320) | 39
[~1571720~](https://www.edrdg.org/jmwsgi/entr.py?svc=jmdict&sid=&q=1571720) | 38
[~2059950~](https://www.edrdg.org/jmwsgi/entr.py?svc=jmdict&sid=&q=2059950) | 38
[~2848157~](https://www.edrdg.org/jmwsgi/entr.py?svc=jmdict&sid=&q=2848157) | 38
[~1601770~](https://www.edrdg.org/jmwsgi/entr.py?svc=jmdict&sid=&q=1601770) | 37
[~2745190~](https://www.edrdg.org/jmwsgi/entr.py?svc=jmdict&sid=&q=2745190) | 37
[~2779470~](https://www.edrdg.org/jmwsgi/entr.py?svc=jmdict&sid=&q=2779470) | 37
[~2847494~](https://www.edrdg.org/jmwsgi/entr.py?svc=jmdict&sid=&q=2847494) | 37
[~1463690~](https://www.edrdg.org/jmwsgi/entr.py?svc=jmdict&sid=&q=1463690) | 36
[~1872660~](https://www.edrdg.org/jmwsgi/entr.py?svc=jmdict&sid=&q=1872660) | 36
[~2255200~](https://www.edrdg.org/jmwsgi/entr.py?svc=jmdict&sid=&q=2255200) | 36
[~2520960~](https://www.edrdg.org/jmwsgi/entr.py?svc=jmdict&sid=&q=2520960) | 36
[~2578560~](https://www.edrdg.org/jmwsgi/entr.py?svc=jmdict&sid=&q=2578560) | 36
[~2719710~](https://www.edrdg.org/jmwsgi/entr.py?svc=jmdict&sid=&q=2719710) | 36
[~2850274~](https://www.edrdg.org/jmwsgi/entr.py?svc=jmdict&sid=&q=2850274) | 36
[~1342030~](https://www.edrdg.org/jmwsgi/entr.py?svc=jmdict&sid=&q=1342030) | 34
[~1387250~](https://www.edrdg.org/jmwsgi/entr.py?svc=jmdict&sid=&q=1387250) | 34
[~1597510~](https://www.edrdg.org/jmwsgi/entr.py?svc=jmdict&sid=&q=1597510) | 34
[~1640500~](https://www.edrdg.org/jmwsgi/entr.py?svc=jmdict&sid=&q=1640500) | 34
[~1783420~](https://www.edrdg.org/jmwsgi/entr.py?svc=jmdict&sid=&q=1783420) | 34
[~2394150~](https://www.edrdg.org/jmwsgi/entr.py?svc=jmdict&sid=&q=2394150) | 34
[~1399890~](https://www.edrdg.org/jmwsgi/entr.py?svc=jmdict&sid=&q=1399890) | 33
[~2083740~](https://www.edrdg.org/jmwsgi/entr.py?svc=jmdict&sid=&q=2083740) | 33
[~2275120~](https://www.edrdg.org/jmwsgi/entr.py?svc=jmdict&sid=&q=2275120) | 33
[~2420070~](https://www.edrdg.org/jmwsgi/entr.py?svc=jmdict&sid=&q=2420070) | 33
[~2202560~](https://www.edrdg.org/jmwsgi/entr.py?svc=jmdict&sid=&q=2202560) | 32
[~2398920~](https://www.edrdg.org/jmwsgi/entr.py?svc=jmdict&sid=&q=2398920) | 32
[~2664780~](https://www.edrdg.org/jmwsgi/entr.py?svc=jmdict&sid=&q=2664780) | 32
[~2826504~](https://www.edrdg.org/jmwsgi/entr.py?svc=jmdict&sid=&q=2826504) | 32
[~2829858~](https://www.edrdg.org/jmwsgi/entr.py?svc=jmdict&sid=&q=2829858) | 32
[~1457250~](https://www.edrdg.org/jmwsgi/entr.py?svc=jmdict&sid=&q=1457250) | 31
[~1796330~](https://www.edrdg.org/jmwsgi/entr.py?svc=jmdict&sid=&q=1796330) | 31
[~2040040~](https://www.edrdg.org/jmwsgi/entr.py?svc=jmdict&sid=&q=2040040) | 31
[~2083280~](https://www.edrdg.org/jmwsgi/entr.py?svc=jmdict&sid=&q=2083280) | 31
[~2120210~](https://www.edrdg.org/jmwsgi/entr.py?svc=jmdict&sid=&q=2120210) | 31
[~2124980~](https://www.edrdg.org/jmwsgi/entr.py?svc=jmdict&sid=&q=2124980) | 31
[~2420190~](https://www.edrdg.org/jmwsgi/entr.py?svc=jmdict&sid=&q=2420190) | 31
[~2756410~](https://www.edrdg.org/jmwsgi/entr.py?svc=jmdict&sid=&q=2756410) | 31
[~2836605~](https://www.edrdg.org/jmwsgi/entr.py?svc=jmdict&sid=&q=2836605) | 31
[~2845765~](https://www.edrdg.org/jmwsgi/entr.py?svc=jmdict&sid=&q=2845765) | 31

**Comment by JMdictProject** [comment]
I think this batch has all been cleaned up.
