### ISSUE TITLE
New version for Classical Japanese 

### ISSUE THREAD

**Issue by devorair790** [JMdictProject/JMdictIssues#108]
Add better support for Classical Japanese (i.e. conjugations)

**Comment by JMdictProject** [comment]
Not really sure what is being requested. JMdict primarily covers contemporary Japanese, and only has a relatively small number of old terms which are typically tagged as [arch]. Old verb forms have POS tags such as "v2a-s" (for 二段活用). Verb inflection/conjugation is not really part of the dictionary.

**Comment by devorair790** [comment]
A new version of JMdict (ie. CJMdict) specifically designed to support Classical Japanese

**Comment by JMdictProject** [comment]
That's a whole new project. It would be good if someone could get it going, but it's beyond the scope of the current project.
