### ISSUE TITLE
Add interface to submit example sentences 

### ISSUE THREAD

**Issue by devorair790** [JMdictProject/JMdictIssues#110]
I don't think there's any interface to submit example sentences for JMdict

**Comment by JMdictProject** [comment]
The example sentences uses by various apps and systems in conjunction with the JMdict entries come from the Tatoeba project. See https://www.edrdg.org/wiki/index.php/Main_Page#The_Tanaka_Corpus

**Comment by devorair790** [comment]
But there's still no interface to submit indexed sentences

**Comment by JMdictProject** [comment]
> But there's still no interface to submit indexed sentences

There is, within the Tatoeba project. Any Japanese sentence can have a set of indices attached. Note that the project usually expects that sentence submissions and amendments are carried out by native speakers.

**Comment by furanzoni** [comment]
> There is, within the Tatoeba project. Any Japanese sentence can have a set of indices attached. Note that the project usually expects that sentence submissions and amendments are carried out by native speakers.

I don't see this interface to add sentences with indices or modify existing sentences' indices within the Tatoeba website. Would be useful so we could help fixing #121.

**Comment by JMdictProject** [comment]
> I don't see this interface to add sentences with indices or modify existing sentences' indices within the Tatoeba website.

https://tatoeba.org/en/sentence_annotations/show/98515 (example)

You need to be logged in.

**Comment by stephenmk** [comment]
If the JMdictDB interface could at least display the number of sentences and priority-tagged sentences that are indexed to entries and senses, I think that would do a great deal to remind people to update the sentence indices when big changes are made.

Just in the past month we've forgotten to update the sentences for [貿易上](https://www.edrdg.org/jmwsgi/entr.py?svc=jmdict&sid=&q=2079970.1) and [チュッ](https://www.edrdg.org/jmwsgi/entr.py?svc=jmdict&sid=&q=2255640.1), for example.

**Comment by JMdictProject** [comment]
The sentences and their indices are quite separate from the dictionary database. What might be more achievable is to have a separate function available which could identify the relationship, if any, between surface forms and sentence indices.

Wwwjdic has code and data files for associating surface forms with the sentences. I could potentially use that to provide such things as:
- a lookup function which reported on the number of sentences linked to a form;
- a report (weekly?) which listed the dictionary indices which did not match any JMdict entry form.
