### ISSUE TITLE
Redundant example sentences

### ISSUE THREAD

**Issue by stephenmk** [JMdictProject/JMdictIssues#115]
I searched the `JMdict_e_examp` file for entries with example sentences that are nearly identical to the entry headwords. I found a couple dozen. These sorts of example sentences are somewhat redundant, so we may want to consider removing the associated priority tags in the Tatoeba database.

Sequence | Headword | SentenceID | Sentence | Meaning
-- | -- | -- | -- | --
1107700 | ファイト | 197239 | ファイトだ。 | Don't give up the fight.
1211360 | 堪忍袋の緒が切れる | 183970 | 堪忍袋の緒が切れる。 | My patience has come to the breaking point.
1217220 | 眼中にない | 183667 | 眼中にない。 | I don't exist to you.
1229820 | 泣き面に蜂 | 182382 | 泣き面に蜂。 | Misfortunes never come singly.
1266470 | 呼吸 | 174577 | 呼吸は？ | Is he breathing?
1294220 | 最低 | 170386 | 最低！ | You're disgusting!
1338260 | 出る釘は打たれる | 147764 | 出る釘は打たれる。 | The nail that sticks up gets hammered down.
1374550 | すごい | 214728 | すごいぞ！ | Terrific!
1448740 | 灯台下暗し | 354110 | 灯台下暗し。 | You can't see the forest for the trees.
1453320 | 同病相憐れむ | 123642 | 同病相憐れむ。 | Misery loves company.
1514120 | 取らぬ狸の皮算用 | 148681 | 取らぬ狸の皮算用か。 | Are you counting your chickens before they are hatched?
1640760 | 窮すれば通ず | 182371 | 窮すれば通ず。 | Necessity is the mother of invention.
1674540 | 明々白々 | 80233 | 明々白々だ。 | It's abundantly clear.
1782980 | 喧嘩両成敗 | 175411 | 喧嘩両成敗。 | It takes two to make a quarrel.
2013650 | 踏んだり蹴ったり | 123893 | 踏んだり蹴ったり。 | It never rains but it pours.
2016860 | 懐が暖かい | 185149 | 懐が暖かい。 | I have plenty of money with me.
2119740 | 何だって | 187857 | 何だって？ | What did you say?
2128500 | もう一踏ん張り | 194281 | もう一踏ん張り！ | Stick to it!
2140010 | 面目丸つぶれ | 80187 | 面目丸つぶれだ。 | I have lost face completely.
2197810 | 無駄口をたたく | 80906 | 無駄口をたたくな。 | Don't waste your breath.
2220750 | 口ばっかり | 173926 | 口ばっかり！ | You're all talk and no action!
2393900 | いい加減にしろ | 229374 | いい加減にしろよ。 | Cut it out.
2547280 | よく言う | 192781 | よく言うよ。 | Don't make me laugh.
2683950 | もうたくさん | 194397 | もうたくさんだ。 | I have had it.
2839342 | 失敗を恐れる | 149586 | 失敗を恐れるな。 | Don't be afraid of making mistakes.

<br><br>
Similarly, I searched for example sentences that are nearly identical to the cross-references within the same entries. I found nine.

Sequence | Headword | Sense | Reference | SentenceID | Sentence | Meaning
-- | -- | -- | -- | -- | -- | --
1194500 | 花 | 7 | 言わぬが花 | 174747 | 言わぬが花。 | "Speech is silver, silence is gold."
1387340 | 先んずる | 1 | 先んずれば人を制す | 141901 | 先んずれば人を制す。 | "First come, first served."
1405750 | 賊軍  | 1 | 勝てば官軍負ければ賊軍 | 147190 | 勝てば官軍負ければ賊軍。 | "If you win, you are in the right, but if you lose, you are in the wrong."
1488460 | 百聞 | 1 | 百聞は一見に如かず | 85412 | 百聞は一見に如かず。 | Seeing is believing.
1742050 | 窮鼠 | 1 | 窮鼠猫を噛む | 182372 | 窮鼠猫を噛む。 | A cornered rat will bite a cat.
2034480 | 身につく | 2 | 悪銭身に付かず | 191400 | 悪銭身に付かず。 | "Ill gained, ill spent."
2106260 | こった | 1 | 何てこった | 187851 | 何てこった。 | Holy cow!
2138820 | 如かず | 1 | 百聞は一見に如かず | 85412 | 百聞は一見に如かず。 | Seeing is believing.
2438770 | 弥立つ | 1 | 身の毛がよだつ | 144747 | 身の毛がよだつ。 | Make one's hair stand on end.

So for example, in the entry for 花 on sense 07, the cross reference and example sentence are currently identical.

![hana](https://github.com/JMdictProject/JMdictIssues/assets/8003332/baf7a2ca-3ba0-48ec-ba01-c8f43846ab47)

**Comment by stephenmk** [comment]
If nobody has any objections within about a week or so, I'll start working through cleaning these up.

**Comment by JMdictProject** [comment]
I'm glad there are only a few, and they should be cleaned up.

I looked in detail at the first two, and they are actually good examples of how such a clean-up could go:
- for ファイト, there is only that one trivial sentence using it. It is useless as an example. I have dropped it entirely (deleted the index from Tatoeba.)
- for 堪忍袋の緒が切れる, there are several sentences using the expression. I added the priority tag (~) to a better sentence, and dropped the old one completely.

So in a clean-up I think the first thing should be to try and identify a more appropriate example sentence and move the tag there. If sentences are useless (as in the ファイト case) they can dropped by removing the index. I use the sentence display option in wwwjdic to help search for possible suitable sentences.

**Comment by stephenmk** [comment]
I deleted all the indices for the top set of sentences. For the bottom set I only removed the priority flags since those sentences are indexed to more than one entry.

> So in a clean-up I think the first thing should be to try and identify a more appropriate example sentence and move the tag there.

Below is a list of the more appropriate example sentences that I picked out. I already set the priority flags on these sentences. If everything looks good then it should be fine to close this issue.

---

[呼吸](https://tatoeba.org/en/sentences/show/169299) [01]
> 酸素は私たちが呼吸すると肺の中に取り込まれる。 
> Oxygen is taken into our lungs when we breathe.

[最低](https://tatoeba.org/en/sentences/show/162261) [01]
> 私は最低２マイルは歩ける。
> I can walk at least two miles.

[最低](https://tatoeba.org/en/sentences/show/217359) [02]
> こんな最低の目にあったことはないわ！
> This is the worst thing that has ever happened to me!

[最低](https://tatoeba.org/en/sentences/show/231211) [03]
> あの映画、最低！
> That movie stinks!

[すごい](https://tatoeba.org/en/sentences/show/204320) [01]
> そんなすごい目で睨み付けないでください。
> Don't look so fiercely at me.

[すごい](https://tatoeba.org/en/sentences/show/172807) [02]
> 今すごい名案がうかんだぞ。
> I've just come up with a great idea.

[踏んだり蹴ったり](https://tatoeba.org/en/sentences/show/189626) [01]
> 雨には降られるわ、デートに遅刻するわ、財布を落とすわ、今日は踏んだり蹴ったりだよ。
> I get caught in the rain, I'm late for my date, and I lose my pocketbook. It's just one thing after another today.

[懐が暖かい](https://tatoeba.org/en/sentences/show/199935) [01]
> トムは今日給料をもらったのでふところがあったかい。
> Tom is flush with money since he got paid today.

[いい加減にしろ](https://tatoeba.org/en/sentences/show/74717) [01]
> いい加減にしろっつの。恵子さん、嫌がってるだろ。
> I said 'Quit it'. Can't you see Keiko hates that?

[もうたくさん](https://tatoeba.org/en/sentences/show/222971) [01]
> この悪い天気はもうたくさんだ。
> We've had enough of this bad weather.

[口ばかり](https://tatoeba.org/en/sentences/show/234618) [01]
> あいつは口ばかりで、誠意がないね。巧言令色少なし仁とはよくいったもんだ。
> They say fine words are no virtue if they're insincere and that's him in a nutshell. He's all talk but doesn't mean a word of it.

**Comment by JMdictProject** [comment]
They look fine. I think this can be closed.
