### ISSUE TITLE
JMdict NG progress and release date

### ISSUE THREAD

**Issue by parfait8566** [JMdictProject/JMdictIssues#116]
Obviously not meant to put any pressure, but just out of curiosity. 
Is there any progress table or something to see how close JMdict NG (next generation) is to a finished product? Are there any ideas of when it'll be release, even roughly?

**Comment by yamagoya** [comment]
I had to take a break from work on the NG version last fall for real life reasons but hope to get back on it in a few weeks.  Only issue coming up is that I will have a bunch of other commitments in March-April time frame that will likely cause a pause.  No promises but maybe early (northern) summer?   It will also depend to some extent on Jim and his ability to fit upgrade time into his schedule.

**Comment by parfait8566** [comment]
I see, thank you

**Comment by JMdictProject** [comment]
I'll close this and open an issue specifically for the discussion of JMdict NG matters.
