### ISSUE TITLE
Kanji check project

### ISSUE THREAD

**Issue by razasyedh** [JMdictProject/JMdictIssues#119]
A while back I cross-checked the readings of our entries against *Daijirin* (and later *GG5* & *Meikyō*). I had the thought of also checking for any possible incorrect kanji. So I matched on readings that only show up once.

Here are the 923 results that differ in the kanji used for these readings, with the JMDict kanji followed by the *Daijirin* one:

[mismatches.txt](https://github.com/JMdictProject/JMdictIssues/files/13927293/mismatches.txt)

As expected, false positives abound. There are also many cases of differing okurigana usage.  As well as cases where substitute kanji are used.

I'll be working through the bunch over time, but mentioning it here for context and if there are any concerns. The issue can be closed after a short while if nothing major comes up.

**Comment by JMdictProject** [comment]
Interesting, but obviously needs some work. The first 4 were false positives. The fifth was useful.

**Comment by razasyedh** [comment]
Agreed, there are tons of homonyms, so this naive approach won't be accurate. (but we'll see how fruitful it ends up being)

In the future, I want to run our entries through Mecab/Unidic to see what that would expect the readings to be, but will likely have to somehow account for *rendaku*, gemination, etc. Using semantic information from this or even Kanjidic would be more precise.

**Comment by JMdictProject** [comment]
I think this one can be closed.
