### ISSUE TITLE
[io] tag - definition and criteria

### ISSUE THREAD

**Issue by JMdictProject** [JMdictProject/JMdictIssues#124]
[An "issue" is being opened for each of the kanji/reading tags to provide a forum for discussing the definitions and criteria for applying the tags. It is intended to be used to assist in the preparation of documentation of the tags.]

The [io] tag is associated with kanji forms and is currently defined as "irregular okurigana usage". It is currently used in 893 entries.

The purpose of the tag is to inform users that the okurigana form is not that which is generally used. The tag is only used on forms which are visible, i.e. does not have an [sK] tag.

An example is the 向こう岸 (opposite bank) entry, which includes the 向う岸 and 向岸 forms, both of which have [io] tags. As they have low n-gram counts (3.8% and 1.9% respectively) they could be made [sK], however as 向う岸 is in 広辞苑 it may be preferable to keep it visible.

**Comment by JMdictProject** [comment]
A page is being developed on the project Wiki which covers these tags, The text of this issue has been transferred there. See: https://www.edrdg.org/wiki/index.php/Kanji_and_Reading_Information_Fields

**Comment by parfait8566** [comment]
The way this tag is being currently used is confusing in my opinion. The other irregular tags are used for forms NOT present in official sources but used in the wild/somewhat relevant. [io] is pretty much used the opposite, for forms present in official sources (like 向う岸 in Kojien, Obunsha and Iwanami's dictionaries) but has low n-gram counts. But it's also sometimes used for genuinely irregular forms, not present in any official source. It's rather inconsistent. 
A rare okurigana tag for the first type of forms would be very beneficial. I don't think an irregular okurigana is that useful. If the form is not used much at all, it can be hidden with [sK]. If it's popular, can you really say it's irregular? As far as I can see [iK] is used if the official sources explicitly say 誤り or if it's an obvious mistake/typo/変換ミス and the same goes for [ik]. Given the flexible nature of how okurigana is used and the permissiveness of many Japanese dictionaries, I don't believe an irregular okurigana tag is that useful.
