### ISSUE TITLE
Additional gloss types

### ISSUE THREAD

**Issue by jimmubreen** [JMdictProject/JMdictIssues#13]
In the 緊急交通路 one of the glosses (emergency road) is noted as the  "official translation", which is useful as it doesn't really mean that in English. Marcus has suggested there could be a gloss type tag to that effect. Worth considering.

He also suggested that "BrE, AmE, AusE, NzE, HKE could also be gloss types". I'm not so sure it's a good idea. It's a messy topic and many English terms don't fit neatly into country categories.

**Comment by robinjmdict** [comment]
I think "trademark" [tm] would be a useful gloss type. We have some entries where the Japanese term isn't trademarked but the gloss is (e.g "sellotape" on セロハンテープ and "Wite-Out"/"Tipp-Ex" on 修正液). Our current solution is to add "(brand name)" or "(trademark)" to the gloss.

**Comment by JMdictProject** [comment]
Just thinking about this one, we already have a "field" tag of [tradem] and 46 entries have it set. I suspect what you mean is something that can go on individual glosses, as we do with [lit].

**Comment by robinjmdict** [comment]
Yes, that's right. The [tradem] field tag indicates that the Japanese term is a trademark. We don't have a tag for indicating that a gloss is a trademark.

**Comment by JMdictProject** [comment]
I'll add a "[tm] trademark"  to the gloss-information fields (along with "fig", "expl", etc.).

**Comment by JMdictProject** [comment]
Done.
