### ISSUE TITLE
Nakaguro forms: [sk] or not.

### ISSUE THREAD

**Issue by JMdictProject** [JMdictProject/JMdictIssues#130]
We currently have about 14k entries, usually involving compound noun or noun-phrase 外来語, with multiple katakana versions with and without the ・ character between the source words. An example is "アーカイブビット; アーカイブ・ビット". 

Usually we have them in that order, with both forms visible. An exception is made for initialisms, e.g. ＶＲＥ, where we have decided to make the ブイ・アール・イー form alone visible.

Although some references, especially JE dictionaries, only show the nakaguro forms, it is clear from the n-grams those forms are generally less common, and in many cases quite rare. This has led to suggestions that the rare nakaguro versions be hidden. It would be good have a clear policy on this to guide submitters and editors.

The options are:
- A. Continue the current approach with both forms visible regardless of usage levels.
- B. Show only the nakaguro form and have the other hidden.
- C. Show only the non-nakaguro form and have the other hidden.
- D. Attempt to establish show/no-show criteria based on n-grams, and selectively add [sk] tags.

FWIW, my view is that we're not facing a "clutter" problem with these terms, and we may as well stay with the status quo (A).

**Comment by rampaa** [comment]
My personal preference is as follows: A > D > B > C

**Comment by robinjmdict** [comment]
I'm think the current approach is fine. I suggested hiding the nakaguro form on the レベルダウン entry because 1) it's not a noun+noun compound, 2) it's often/usually 〜する, and 3) GG5 doesn't have nakaguro for it. My instinctive reaction to レベル・ダウン is that it looks odd (whereas something like ドッグ・フード does not).

**Comment by JMdictProject** [comment]
OK, we'll stick with the current approach.

I'm not sure about hiding レベル・ダウン, etc.  We have heaps of 〜ダウン and 〜アップ entries; they're sort verb+verb-particle combinations,  and I'd treat them like the noun-noun ones. The nakaguro versions are rarely common.

**Comment by JMdictProject** [comment]
Can close this one now.
