### ISSUE TITLE
CJK Compatibility symbols in entries 

### ISSUE THREAD

**Issue by JMdictProject** [JMdictProject/JMdictIssues#131]
I would like to clarify the issue of the use of the CJK Compatibility symbols in entries (https://en.m.wikipedia.org/wiki/CJK_Compatibility). These are the symbols representing units such as μA, blocks of katakana  such as ㌀, etc. There has been some consideration of adding these to equivalent entries, e.g. as hidden surface forms.

While it is possible to add these characters to entries, and to use them as search keys,  I see no real advantage in doing so. They do not seem to be used very much at all, and never in text. I propose that we adopt a policy of not including them in entries.

**Comment by stephenmk** [comment]
If app developers want to include these forms in their apps, it's not a huge ordeal to map the codepoints to the respective JMdict entries manually. I think the 10ten web browser extension already does this, for example.

**Comment by JMdictProject** [comment]
Can close this now.
