### ISSUE TITLE
Idea: tags for 季語

### ISSUE THREAD

**Issue by nicolasmaia** [JMdictProject/JMdictIssues#14]
Quite a few sources list words that are 季語. Would it be worthwhile to have that information in JMdict as well?

**Comment by jimmubreen** [comment]
I think that would be OK. A misc attribute of "seas", with a description of "seasonal word (in haiku)".

**Comment by nicolasmaia** [comment]
Even better I feel is if the tag would explicitly state which season it alludes to.

**Comment by jimmubreen** [comment]
I don't think that's necessary. Usually it's obvious from the entry, e.g. 春の山. Better not to have at least 4 tags.

**Comment by nicolasmaia** [comment]
A lot, maybe even most times it's not obvious. See a few random entries from this list: https://ja.wikipedia.org/wiki/%E5%AD%A3%E8%AA%9E%E4%B8%80%E8%A6%A7

**Comment by jimmubreen** [comment]
I think that list is a bit far-fetched in spots. For example, in the 春の季語 block it has a 行事 section containing 卒業式, 入学式 and 入社式. I can't imagine tagging those entries as season words.

**Comment by Marcusjmdict** [comment]
A LOT of words are considered kigo in haiku. I think [seasonal] by itself isn't very helpful, if there's going to be any point to it, you need to include the specific season. I'm not sure I think this belongs in a general Japanese-English dictionary though.

**Comment by JMdictProject** [comment]
I think we can put this in the "closed" group now.
