### ISSUE TITLE
Clarification regarding JMnedict policy

### ISSUE THREAD

**Issue by parfait8566** [JMdictProject/JMdictIssues#141]
I'm not sure if I failed to find the JMnedict equivalent of the JMdict editorial wiki or it just doesn't exist. Anyway, I had a doubt regarding the policy.
When it comes to place names, pretty much all Japanese dictionaries tend to give a brief geographical description. Let's say 網走, they mention that it's a city (or was a former subprefecture) in eastern Hokkaido. These descriptions seem very useful to me. Is submitting edits for this sort of info allowed or is it deemed out of scope for the dictionary? If it's the latter, I believe the policy should be reconsidered.

**Comment by JMdictProject** [comment]
There isn't an editorial policy as such. The names collection was scraped together years ago from the WWW and its predecessors. The quality of much of it is quite low. We've developed informal style practices for some of the name types.

I wouldn't object to slightly more information being added to, say, Japanese place names, as suggested for 網走.

**Comment by parfait8566** [comment]
Okay, thanks.
