### ISSUE TITLE
Broaden [m-sl] - manga slang tag

### ISSUE THREAD

**Issue by parfait8566** [JMdictProject/JMdictIssues#147]
I propose we convert the [m-sl] tag so it covers otaku media (anime, manga, videogames, etc.) or culture in general

**Comment by Marcusjmdict** [comment]
I think we've already decided on something similar: to retire [m-sl] and replace it with a new [manga] tag. See #68 
Or maybe we never decided on it formally?

**Comment by parfait8566** [comment]
My bad, didn't see it had already been discussed. 
I'll assume the scope of the tag will be expanded to anime, manga, videogames, etc. sooner or later and close this issue.

**Comment by JMdictProject** [comment]
Some stats:
[col]  - 1,876 entries
[sl] - 1,205 entries
[m-sl] - 35 entries
[net-sl] - 300 entries

I see there are already anime terms such as ラッキースケベ among the [m-sl] entries.

I wouldn't mind it being broadened to include terminology mainly used in popular culture such as manga, anime, video games, etc.

Marcus has pointed to earlier discussions (#68 and #41) which I had completely forgotten.
