### ISSUE TITLE
Glossing style for people in JMnedict

### ISSUE THREAD

**Issue by parfait8566** [JMdictProject/JMdictIssues#148]
Not sure if this has been discussed before.
Currently the glossing style for people seems to include both day of birth and death. I don't understand the usefulness of including month and day, year of birth strikes me as good enough. I'm not sure the year of death is necessary either and its inclusion means that every time someone present in the database dies we would need to update the entry accordingly. Couldn't a simple format be adopted instead?

**Comment by JMdictProject** [comment]
I think you are referring to the names dictionary (JMnedict); not JMdict, which only has a handful of entries for people.

Of the 50k+ [person] entries in JMnedict around 20-30% have dates. For historical people they tend to be just the years, e.g. "Genghis Khan (1162-1227)", and for more recent people we often have more detail, e.g. "George Kawaguchi (1927.6-2003.11; jazz musician)".  To be frank, I don't have a problem with this. We've never had a mandated or even recommended format. It's really up to the person who puts in an entry or makes an edit.

**Comment by parfait8566** [comment]
> I think you are referring to the names dictionary (JMnedict); not JMdict, which only has a handful of entries for people.

Yeah, maybe I should have mentioned this in the post and not only in the title.

> We've never had a mandated or even recommended format. It's really up to the person who puts in an entry or makes an edit.

I think that for the sake of consistency it'd be better to follow just one format.
As far as I can see, dictionaries like Daijirin and GG5 just stick to birth year and death year with no month or day being included. It's also easier to read with only the years, e.g.  "George Kawaguchi (1927-2003; jazz musician)" seems more immediate to me compared to "George Kawaguchi (1927.6-2003.11; jazz musician)". I don't believe the death year is necessary either, but at least there seem to be "precedents" for it.

**Comment by birtles** [comment]
For what it's worth, 10ten uses this information to display the person's age which I find very helpful when reading the news:

![image](https://github.com/user-attachments/assets/7b6ec478-1844-4f08-83ed-9ba85fae6276)

It copes somewhat with incomplete birthdates too but it's nicer if it can give an exact age:

![image](https://github.com/user-attachments/assets/e06ce61a-7008-41d5-8ad7-ed1c8fb5206d)

It's also useful to have the date of someone's passing so it doesn't try to show their age in that case.

**Comment by parfait8566** [comment]
That's an interesting use case I didn't consider.

**Comment by parfait8566** [comment]
> It's also useful to have the date of someone's passing so it doesn't try to show their age in that case.

Just an idea, but Wikipedia does show the age even if the person is dead:

![image](https://github.com/user-attachments/assets/6d8ba0b7-01c8-446a-ba47-f8d7feb1fe3a)

This is how it shows the full dates if the person is dead:

![image](https://github.com/user-attachments/assets/7bef114c-5f03-490e-9638-50b6d3431ef6)

If alive:

![image](https://github.com/user-attachments/assets/8acb4052-bed3-4b27-a376-5beada7dd696)

I guess the full date approach is useful for sites and applications, but in my opinion they might consider showing them in a more immediately readable fashion.

**Comment by JMdictProject** [comment]
As I just commented on the モーツァルト entry, for long-dead historical figures, I think just the years of their life are enough. I changed that entry to Wolfgang Amadeus Mozart (1756-1791....).

**Comment by parfait8566** [comment]
I think that ideally JMnedict entries should be linked to the Wikipedia articles so they're always accurate and up-to-date. Maybe an idea for a rework in the future,
