### ISSUE TITLE
Use of French, etc. diacritics in glosses

### ISSUE THREAD

**Issue by jimmubreen** [JMdictProject/JMdictIssues#17]
Something that is being handled a bit inconsistently at present is the issue of whether terms from other languages (especially French) have diacritics or not. For example, we have 10 entries where the gloss contains "cafe" and 13 where it contains "café". In some of the latter cases it is part of a clearly French phrase (café au lait, café brûlot) and in others it's used in an English context, e.g. "themed café where patrons ...".
Then there are cases where we have both, e.g. ペタンク has "pétanque; petanque" and デジャブ has "déjà vu; deja vu". We can't rely on English dictionaries too much. For シネマテーク, which currently has a proposed edit, the OED has "cinematheque, also cinémathèque".
Should we aim for consistency, and if so, what rules should we apply? A couple I would suggest for starters are:
- don't have duplicated versions with and without diacritics (years ago I was concerned about enabling lookups using the English word(s) but I don't think it's a major issue.)
- where a word is thoroughly assimilated into English without diacritics, use that form (this would mean changing a few of the "café" entries to "cafe".
- where gloss contains or is a phrase in another language, retain the original orthography (e.g. 三一致: règle des trois unités).

They're the simpler ones, but the cases like cinematheque or cinémathèque for シネマテーク are less clear.

**Comment by robinjmdict** [comment]
That sounds OK to me.

But at what point is a word "thoroughly assimilated into English without diacritics"? I suspect there are a lot of words/expressions commonly written without diacritics in informal writing that are usually written with diacritics in formal writing. "Déjà vu" probably falls into this category.

**Comment by jimmubreen** [comment]
Yes, there are many words one sees both ways, such as café/cafe. OTOH, it's never hôtel or rôle.
I'd certainly like to clear up the café/cafe and pétanque/petanque duplication. I see we are all over the place with papier mâché/paper mache (sic) too.

**Comment by JMdictProject** [comment]
I have tidied up papier-mâché and pétanque. May as well close it.
