### ISSUE TITLE
[place] → [organization] on 〜大学 entries

### ISSUE THREAD

**Issue by robinjmdict** [JMdictProject/JMdictIssues#19]
I noted in the イエール大学 submission that most of our 〜大学 entries in JMnedict are tagged as [place] when they should be [organization]. Can we use the bulk update script to change them all at once?

**Comment by JMdictProject** [comment]
That can be done - I just tested it. Over 700 of the 〜大学 entries are marked as [place]. I'll try and get to changing them soon.

**Comment by JMdictProject** [comment]
OK, I have updated ~700 entries containing "University". There are about 300 more with 大学 in them which are colleges, institutes, etc. Some need zapping and a few are actual places, but most can change too.

**Comment by JMdictProject** [comment]
I've done another ~350 大学 entries (those with Institute and College.)

**Comment by JMdictProject** [comment]
I think this can be closed. They all seem to be changed.
