### ISSUE TITLE
Addtional field tags

### ISSUE THREAD

**Issue by jimmubreen** [JMdictProject/JMdictIssues#2]
"phil" - philosophy term (e.g.http://www.edrdg.org/jmdictdb/cgi-bin/entr.py?svc=jmdict&sid=&q=2830307)

**Comment by jimmubreen** [comment]
Picsi wrote (#10):
Maybe instead of clunkily adding notes do denote words that are trademarks, we could perhaps have a tag for it.

**Comment by nicolasmaia** [comment]
What's the holdup for implementing this?

**Comment by jimmubreen** [comment]
Recent suggestions: geography and meteorology.
I'll check the front-matter of GG5 where they have a long list.

I hope to get some extra tags added in a few weeks.

**Comment by jimmubreen** [comment]
A month or so back I started looking at a page at the front of GG5 where there is a table of tags, and their meanings, e.g. "【遺】 -> 遺伝学". There are 59 tags listed, and when I looked closely it seemed bizarre. There was a 【狩】 tag for hunting terms, but nothing for 音楽. Then it dawned on me - this table was just for the single-kanji abbreviated tags; the multicharacter ones were not there. So I went through the text of all the GG5 entries (I have a file of it) and stripped out the tags. There are actually almost 1,000 of them. It's probably not a very useful list to try and draw from, but I'll check them for frequency and see if any useful ones pop up.

**Comment by robinjmdict** [comment]
Wow, I had no idea there were that many. We certainly don't need anything close to 1000. But I suppose starting with a lot of field tags and dropping the ones we don't need is better than realising later that we missed some important ones.

Might be worth creating a Google doc with a list of them (sorted by frequency) so that editors can mark the ones they think are worth adding.

**Comment by jimmubreen** [comment]
I have done a quick scripted analysis of the GG5 tags by counting how often they're used in the dictionary and then sorted the counts into descending order. Almost all of the first 25 or so align with the current JMdict tags, and almost all our tags are somewhere in the first 100. I've made up a spreadsheet with comments, etc. and I'll try putting it on Google Sheets. For the moment it will be for editors to see/comment/etc.

**Comment by jimmubreen** [comment]
I've just added 35 new field tags. Go to the Advance Search page, where they are listed about halfway down.
