### ISSUE TITLE
Suggested changes to current field tags

### ISSUE THREAD

**Issue by robinjmdict** [JMdictProject/JMdictIssues#25]
I have a few suggestions regarding existing field tags.

I think the field name for [met] should be meteorology. It's currently "climate, weather". "Meteorology" is simpler (one word rather than two) and it's what other dictionaries use (e.g. Oxford and Collins).

I don't think psychology and psychiatry should share a single tag. They're separate fields. I suggest [psy] for psychiatry and [psych] for psychology.

I think the field name for [archit] should just be "architecture" (currently "architecture, building"). Unless I'm missing something, "building" seems redundant.

Finally, some minor style changes I'd recommend: video game -> video games, audio-visual -> audiovisual, horse-racing -> horse racing.

**Comment by jimmubreen** [comment]
That all seems fine. I'll try and get onto it next week.

If anyone has additional field names to suggest, now is a good time to do it.

**Comment by robinjmdict** [comment]
I suggested one for railway terms a few months back. Haven't thought of any others since then.

One other very minor thing that I might as well mention here. On JMdictDB, when there are multiple field tags on a single sense, the field names are separated by commas without spaces. This results in inconsistent spacing whenever one or more of the field names contains a comma. Easily fixed by including a space after the comma separator, or, alternatively, putting each field name in its own pair of curly brackets (e.g. {food, cooking}{trademark}). I think I prefer the latter.

<img width="306" alt="Screenshot 2021-03-05 at 18 21 06" src="https://user-images.githubusercontent.com/62225444/110157017-9c655e00-7ddf-11eb-9055-51218761e3b1.png">
<img width="364" alt="Screenshot 2021-03-05 at 18 15 56" src="https://user-images.githubusercontent.com/62225444/110183175-304a2080-7e06-11eb-9603-f30f562b18ee.png">

**Comment by jimmubreen** [comment]
I'm making up a consolidated list of proposed changes to field tags

NEW
rail     railways  (proposed by Robin in issue #22.)
psy    psychiatry  

CHANGES
archit  architecture (drop "building")
audvid   audiovisual (drop hyphen)
horse   horse racing (drop hyphen)
met    meteorology  (was "climate, weather")
psych  psychology   (splitting out psychiatry)
vidg   video games (amended)

Any more?

**Comment by robinjmdict** [comment]
Maybe one for clothing [cloth]? 217 terms in GG5 tagged as【服装】.
I think "railways" should be "railway" (no "s").

**Comment by JMdictProject** [comment]
Both these changes are now live.

**Comment by JMdictProject** [comment]
Closing. Can be reopened if needed.
