### ISSUE TITLE
Add an attribute for words that take a number as a direct prefix

### ISSUE THREAD

**Issue by clindsay3** [JMdictProject/JMdictIssues#26]
I’m not sure what the linguistic term for it is, but it would be nice to have a tag for words that accept a number as a direct prefix. Some of these are covered by the “counter” part of speech currently, but not all. 

For example, a word like 時間 is just listed as a noun, but you count them differently than other nouns.  １時間, not 時間１つ.  Another example of a noun like this is 分. Others are listed as suffixes, like 時. It’s not just temporal words, as words like キログラム also fall in this bucket. It looks like there was a little bit of [discussion on this a few years back](http://www.edrdg.org/jmdictdb/cgi-bin/entr.py?svc=jmdict&sid=&e=1993634).

This seems like a distinct enough property of a word that it would merit some sort of attribute in JMdict. From a practical perspective, I’m actually making use of this distinction in the tokenization and furigana-generation parts of my app, and currently just use the “counter” part of speech, and hardcode a list of other words that should be treated the same way.

**Comment by polm** [comment]
These are marked as 助数詞可能 in UniDic, so it shouldn't be hard to build a list at least. Check column `pos3` [here](https://share.streamlit.io/polm/fugashi-streamlit-demo/main/demo.py).

**Comment by clindsay3** [comment]
@polm thank you, that's a huge help!

**Comment by jimmubreen** [comment]
As I mentioned in the comments on the 時間 entry, they are units of measurement, and yes UniDic flags them as 助数詞可能. Despite the "助数詞" they are not really counters in the usual sense.

I can't really see a reason why they'd need labelling in a general dictionary, especially when a specific morpheme lexicon such as UniDic is available to aid tokenizing.

**Comment by clindsay3** [comment]
My primary interest in it is certainly as an aide for tokenization, and the presence of this information in UniDic pretty much alleviates that need. 

My gut is still that it does make sense in a general dictionary, as a piece of information about how a word fits grammatically into a sentence, much like any other part of speech tag. But I will defer to your judgment and can close this issue if you feel like it's not a good fit for the dictionary.

**Comment by jimmubreen** [comment]
It's a fair point. We could certainly create a new POS attribute such as [unit] which could go in the entries for these sorts of terms. Many could be added in bulk using the UniDic data as a source (キロジュール, キログラム, etc.). We already have a [num] tag which is used with about 100 entries dealing with abstract numbers. Does anyone think the creation and addition of a "unit" tag would be useful?

**Comment by Marcusjmdict** [comment]
I think that could be useful.

**Comment by JMdictProject** [comment]
I've moved this to a "new POS tag" issue for now.
