### ISSUE TITLE
When to use the [hist] tag

### ISSUE THREAD

**Issue by JMdictProject** [JMdictProject/JMdictIssues#28]
About 200  entries have the "hist" (historical) tag. When the tag was introduced I think its purpose was to indicate that the term referred to an object, etc. which is no longer in use. Examples of this include 冕冠, 大鎧 and 捕り縄. This is different from the [obs] tag which is used to indicate that the term is no longer the current one used for the object, etc.

The [hist] term has also come to be used for past events such as 壬辰倭乱 where the gloss indicates it was 400 years ago, and things like government positions where the gloss indicates it was used in the Edo period or under the ritsuryo system. I think we need to decide whether the tag is needed or appropriate for such entries. To a large extent, the historical nature is implicit in the gloss.

**Comment by robinjmdict** [comment]
I'd always assumed that historical government positions, laws, taxes, etc. were the sorts of things (in addition to tangible objects) that "hist" was designed for.

I wouldn't have said that "hist" was necessary for events but I see that GG5 tags historical events as【日本史】or【史】.

As an aside, I quite like GG5's approach of using a separate tag for Japanese history and I'd be in favour of adding one to JMdict.

**Comment by JMdictProject** [comment]
OK, so we leave [hist] being used for both no-longer-used objects, etc. and also for events such as the 薔薇戦争.
I'll add (say) [histj] - event in Japanese history, to the list of field names under consideration.

**Comment by JMdictProject** [comment]
I have updated the information at https://www.edrdg.org/wiki/index.php/Editorial_policy#Old_and_Rarely_Used_Terms to indicate that the "hist" tag can be used with terms that are in current use.
