### ISSUE TITLE
Additional JMnedict name types

### ISSUE THREAD

**Issue by jimmubreen** [JMdictProject/JMdictIssues#3]
Nicolas Maia has proposed "笠戸丸 [かさとまる] /(unclass) Kasato Maru (ship)/" We probably need an "object" type for these.

**Comment by jimmubreen** [comment]
picsi proposed the following issue (#8)
________________________________
jmnedict: tag for mythical or fictional entities

Tags for things like these would be useful:

https://www.edrdg.org/jmdictdb/cgi-bin/entr.py?svc=jmdict&sid=&e=1995876
https://www.edrdg.org/jmdictdb/cgi-bin/entr.py?svc=jmdict&sid=&e=1998801

Perhaps under one tag, something like 'mythical or fictional entity'.
__________________________________

I agree we need something like that. If possible it would be good to have a tag which could be used for people, animals, demons, beasts, etc. in fiction and mythology. Possibly "character" would do?

**Comment by jimmubreen** [comment]
I'd like to start settling on a set of additional name types. I don't think we need a lot, but there are some gaps that need filling. 

My suggestions are:
object - we are missing this at the moment.
deity - useful for entries like ヂュピター, ヴィナス, etc.
myth(ological) - for places, etc. occurring in myths, floklore, etc.
char(acter) - specifically for characters in works of fiction, games, etc.

Note that these name-type tags can work together, so that something like アトランティス/アトランチス could be tagged [myth,place].

**Comment by robinjmdict** [comment]
Looks good to me.

I have a few questions/proposals after looking through our "unclassified" name entries.

Do we need a new tag for  銀座線, 上越新幹線, etc.? They're not places or objects. Would [service] work? サンダーバード is another unclassified entry glossed as "Thunderbird (limited express train service operating between Osaka and Kanazawa)".

Would things like 吸魂鬼 (dementor in Harry Potter) and クリパー (Creeper in Minecraft) come under "character"? They're types of creature rather than specific characters.

Do we want a "fiction" tag that can be used with object, place, etc.? (e.g. タケコプター = [object, fiction])

Any ideas for 気候変動枠組条約, ＩＥＬＴＳ, ハギビス, and 森友学園問題? I'm not sure the last one should be in the names dictionary.

**Comment by JMdictProject** [comment]
Very useful comments, and certainly point to some additional name types that would be useful.

service - applies to things like ＩＥＬＴＳ and possibly 銀座線, etc.
event - covers things like 森友学園問題, ハギビス, etc.
fiction - really a qualifier/modifier to use with other tags such as object, place, etc. (as suggested). The "myth" tag can work the same way.
other - this is really to have as a catch-all, signalling that it's been looked at and doesn't fit in with the established types, whereas "unclassified" includes those not assessed/allocated.

気候変動枠組条約 is an interesting one. Maybe "other" will do?

**Comment by JMdictProject** [comment]
This is an attempt to consolidate the possible additions/changes to the names types.
First I suggest the following tags which would be used in association with others such as [object], [person], [event], etc. to provide some context. If they are nor used it indicates that the thing being named is/was real.
[fiction]  (occurs in a work of fiction)
[myth]
[legend]
[relig] (occurs in the beliefs or texts of a religion.)

Then there are the additional named-entity tags:
[service]
[event]
[object]
[character]
[creature]  
[deity]   (This is for clarity. ヴィーナス is currently "person". We could just add [relig], but having a specific tag is clearer)
[other]
Feedback, please, as I'm starting work on the impementation of these.

**Comment by robinjmdict** [comment]
Looks good to me. 

A couple of comments:

Should a mythical being that isn't a deity be tagged be tagged as [myth, creature]?

Do [character] and [deity] stand on their own or should they be used in conjunction with [fiction] and [religion]? The context texts don't provide any extra information in this case but maybe we want to have all characters and deities tagged as fiction/religion anyway.

A minor thing, but for the sake of consistency can we decide on whether the context tag (fiction, religion, etc.) or type tag (object, place, etc.) should come first when both are used on the same entry. I think I prefer [type, context] (e.g. [object,fiction]). This is assuming that the context and type tags aren't treated differently at the system level (like PoS tags and field tags in JMdict).

**Comment by robinjmdict** [comment]
Do [fiction], [myth], etc. *have* to be used with [object], [person], etc.?  I see that デストロン was just added, which is neither a character nor a creature. Could we just leave it as [fiction], putting any extra information in the gloss if need be? I feel that [other] isn't necessary in cases like this.

**Comment by JMdictProject** [comment]
Just some comments in reply to Robin's questions:
> Should a mythical being that isn't a deity be tagged as [myth, creature]?

Yes, or even [myth, person] - perhaps バルキリー/Valkyrie comes into that grouping. (I don't think Brunhilde is either a creature or a goddess.)

> Do [character] and [deity] stand on their own or should they be used in conjunction with [fiction] and [religion]?

I think [deity] can stand alone. As for [character], I admit I was thinking of [fiction] as a context but maybe it's not needed. I don't think you'd use it when referring to someone in a myth/legend/religious text.

> for the sake of consistency can we decide on whether the context tag (fiction, religion, etc.) or type tag (object, place, etc.) should come first when both are used on the same entry.

The order it appears is the one in which it was entered. I just tested it on my testing copy, and if you put in [fiction,object] that's what you get.

> Do [fiction], [myth], etc. have to be used with [object], [person], etc.?

Not if they exist(ed) in "real" life, which is really the default.

>  I see that デストロン was just added, which is neither a character nor a creature. 

I guess we need to decide whether things like robots, transformers, etc. are characters, creatures or objects. I would have thought [fiction,object] for デストロン.

< Could we just leave it as [fiction], putting any extra information in the gloss if need be? I feel that [other] isn't necessary in cases like this.

Just [fiction] doesn't say much, apart from indication it's something or somewhere made up. We've been discussing Shangri-La (currently in JMdict), and I'd label it [fiction,place]. I think I'd like [fiction] to be used only for context. You wouldn't need to use it for a [work]

**Comment by robinjmdict** [comment]
> Just [fiction] doesn't say much, apart from indication it's something or somewhere made up. We've been discussing Shangri-La (currently in JMdict), and I'd label it [fiction,place]

I was thinking specifically about fictional things that don't fit neatly into one of the name types. There probably aren't many of these, though. As for デストロン, Transformers are living entities, so unless we want to add a [being] tag, [creature] is probably close enough.

> The order it appears is the one in which it was entered. I just tested it on my testing copy, and if you put in [fiction,object] that's what you get.

OK. So should we lead with the contextual tags? [fiction,object] over [object,fiction]? I know it's not terribly important but it's good to stick to a consistent style.

**Comment by JMdictProject** [comment]
[Sorry. I wrote the text below some days ago, but seem to have forgotten to send it. Jim]

Just some comments in reply to Robin's questions:
> Should a mythical being that isn't a deity be tagged as [myth, creature]?

Yes, or even [myth, person] - perhaps バルキリー Valkyrie comes into that grouping. (I don't think Brunhilde is either a creature or a goddess.)

> Do [character] and [deity] stand on their own or should they be used in conjunction with [fiction] and [religion]?

I think [deity] can stand alone. As for [character], I admit I was thinking of [fiction] as a context but maybe it's not needed. I don't think you'd use it when referring to someone in a myth/legend/religious text.

> for the sake of consistency can we decide on whether the context tag (fiction, religion, etc.) or type tag (object, place, etc.) should come first when both are used on the same entry.

The order it appears is the one in which it was entered. I just tested it on my testing copy, and if you put in [fiction,object] that's what you get.

> Do [fiction], [myth], etc. have to be used with [object], [person], etc.?

Not if they exist(ed) in "real" life, which is really the default.

>  I see that デストロン was just added, which is neither a character nor a creature. 

I guess we need to decide whether things like robots, transformers, etc. are characters, creatures or objects. I would have thought [fiction,object] for デストロン.

< Could we just leave it as [fiction], putting any extra information in the gloss if need be? I feel that [other] isn't necessary in cases like this.

Just [fiction] doesn't say much, apart from indication it's something or somewhere made up. We've been discussing Shangri-La (currently in JMdict), and I'd label it [fiction,place]. I think I'd like [fiction] to be used only for context. You wouldn't need to use it for a [work]

**Comment by JMdictProject** [comment]
Closing in on the implementation of these extra name types. Below are the additions in the form of:
- the short form used to input/edit and entry
- the longer form which appears in the XML entities
- the abbreviation used in the ENAMDICT legacy edition

char    character   ch
creat    creature    cr
dei   deity   dei
ev   event   ev
fict    fiction fic
leg  legend  leg
myth    mythology   myth
obj  object  obj
oth   other   oth
relig   religion    rel
serv    service serv

**Comment by robinjmdict** [comment]
> [Sorry. I wrote the text below some days ago, but seem to have forgotten to send it. Jim]

No, you did send it. And I responded again.

**Comment by JMdictProject** [comment]
So you did. When I looked at the page the text was sitting there looking unsent. Maybe a GitHub wobble.

**Comment by robinjmdict** [comment]
Is it necessary to have abbreviations for deity, event, object, etc. when [organization], [company], [person] etc. are written out in full? It's not a big deal, of course; it's just that I know I'm going to have to keep looking them up as I don't edit JMnedict very often.

**Comment by JMdictProject** [comment]
"organization" was a bit of an accident. I meant it to be truncated like "fem" and "masc".
I must admit I find it a chore typing the whole thing - I'd rather it was "org".
Changing it is easy. These tags are in the database as numbers, and the associated text is in  a table.

**Comment by JMdictProject** [comment]
Robin has suggested a "group" name type, to cover things like music groups, as it would be better than "organization".
We have a few of these - グースハウス, 光ＧＥＮＪＩ. 三ばか大将, etc.

**Comment by jimmubreen** [comment]
Another suggestion from Robin in 核不使用声明 to have a "document" (doc?) name type. Sounds good. It's time to add some more.

**Comment by JMdictProject** [comment]
OK, I'm gearing up to add some more name types. So far:
doc - document
group - group

Any more?

**Comment by JMdictProject** [comment]
These have now been added. I'll close the issue; it can be reopened if more are suggested.
