### ISSUE TITLE
Person name structure in JMnedict

### ISSUE THREAD

**Issue by JMdictProject** [JMdictProject/JMdictIssues#30]
I would like to propose the following structure for person names in the names dictionary:

(a) for entries consisting of the surname alone, having the general surname as the first sense, and specific people of that name following in separate senses, For example:
バッハ
[surname] Bach
[person] Bach, Johann Sebastian (1685-1750), German composer
[person] Bach, Carl Philipp Emanuel (1714-88), German composer
[...]

Our current ブルックナー entry, which has "[surname] Bruckner (19th-century Austrian composer)" would become:
ブルックナー
[surname] Bruckner
[person] Bruckner, Anton (1824-96), Austrian composer

(b) for entries consisting of both given and family names, we would use the Japanese transliterations with and without nakaguro and the basic name, date, etc. information, e.g. 
ヨハンゼバスティアンバッハ; ヨハン・ゼバスティアン・バッハ
[person] Johann Sebastian Bach (1685-1750), German composer

At some stage, it would be good to get cross-references sorted out in the names dictionary, but one step at a time.

**Comment by Marcusjmdict** [comment]
I missed this thread but since a couple of years back, and as I suggested recently in the イチロー entry here https://www.edrdg.org/jmdictdb/cgi-bin/entr.py?svc=jmdict&sid=&e=2147607, my preference is for

ヨハンゼバスティアンバッハ; ヨハン・ゼバスティアン・バッハ
[person] Johann Sebastian Bach (1685-1750; German composer)
(the semi-colon needs to be escaped with a `\` of course)

and

バッハ
[surname] Bach
[person] Bach, Johann Sebastian (1685-1750; German composer)

**Comment by JMdictProject** [comment]
I'm comfortable with that. Let's do it that way.

**Comment by birtles** [comment]
It would be good to standardise the date formats too. Currently we have:

`yyyy.m(.d)`:
* `Taro Kono (1963.1.10-; Japanese politician)`
* `Oota Hikari (1965.5.13-)`
* `Edano Yukio (1964.5-)`

`m.d.yyyy`:
* `Kei Komuro (10.5.1991-; lawyer who married Princess Mako)`
* `Mako Komuro (10.31.1991-; former imperial princess)`

**Comment by Marcusjmdict** [comment]
That's my bad, the Komuros being nonstandard. I'll fix them. yyyy.m.d is our standard.

**Comment by JMdictProject** [comment]
I fixed a few more.

**Comment by birtles** [comment]
> That's my bad, the Komuros being nonstandard. I'll fix them. yyyy.m.d is our standard.

@Marcusjmdict it looks like we now have `Mako Komuro (1991.31.10-; former imperial princess)` , i.e. yyyy.**d**.m.

(Also, I notice we're inconsistent about whether we use `mm` vs `m`. e.g. we have `Yūki Tsunoda (2000.05.11-; racing driver)` with the zero-padded `05` but most other places we don't zero-pad, e.g. `Keiko Komuro (1972.8.18-)`. I think we generally _don't_ zero pad but I notice a few other exceptions like `Vincent van Gogh (1853.03.30-1890.07.29)` where we do.)

**Comment by JMdictProject** [comment]
Thanks. I fixed the 旧姫 entry. I don't think the zero-padding is needed. There are about 20 entries with it but it's hardly worth the effort fixing them.

**Comment by birtles** [comment]
> Thanks. I fixed the 旧姫 entry. I don't think the zero-padding is needed. There are about 20 entries with it but it's hardly worth the effort fixing them.

Thank you! (I submitted an update for Kei too.)
Yes, I agree about the zero padding not being worth the trouble.
