### ISSUE TITLE
Additional field tags, June 2021 -

### ISSUE THREAD

**Issue by JMdictProject** [JMdictProject/JMdictIssues#31]
[histj] - event in Japanese history   (from the now-closed discussion on the use of [hist].)

**Comment by JMdictProject** [comment]
Not an additional field but a change: pharm to be described as "pharmacology" rather than "pharmacy".
See https://www.edrdg.org/jmdictdb/cgi-bin/entr.py?svc=jmdict&sid=&q=2714970

**Comment by JMdictProject** [comment]
Just noting that we need to review the entries with the "pharm" tag once it is redefined. I'm not sure all are appropriate.

**Comment by JMdictProject** [comment]
Robin has suggested a mining tag. (entry  2850662)

**Comment by Marcusjmdict** [comment]
We should probably have a kabuki tag. We have 134 entries with the word "kabuki" in them.

**Comment by Marcusjmdict** [comment]
Plenty of Noh-related entries too.

**Comment by Marcusjmdict** [comment]
[politics]?

**Comment by JMdictProject** [comment]
Robin suggests "stock market" in http://www.edrdg.org/jmdictdb/cgi-bin/entr.py?q=2851993&svc=jmdict&sid=
Time I moved on these.

**Comment by JMdictProject** [comment]
Robin also: Proposing we add a film/TV tag. 79 entries tagged as【映】in GG5.
http://www.edrdg.org/jmdictdb/cgi-bin/entr.py?q=1022320&svc=jmdict&sid=

**Comment by JMdictProject** [comment]
Proposed that a "manga" field tag replace the "m-sl" misc tag. (#41)

**Comment by JMdictProject** [comment]
Robin has proposed a [ski] tag.

**Comment by robinjmdict** [comment]
Proposing we add a tag for psychoanalysis. There are 110 terms tagged as【精神分析】in GG5.

We recently added a Greek mythology tag. For the sake of completeness/consistency, I think it's worth having one for Roman mythology as well. If エロス gets a field tag, キューピッド probably should too.

**Comment by JMdictProject** [comment]
Thanks. I'm long overdue on moving on these. I hope to get to it soon.

**Comment by JMdictProject** [comment]
Now being handled in #68
