### ISSUE TITLE
Rare terms in the 国語辞典

### ISSUE THREAD

**Issue by JMdictProject** [JMdictProject/JMdictIssues#33]
This issue was raised by Robin the 京烏  entry (https://www.edrdg.org/jmdictdb/cgi-bin/entr.py?svc=jmdict&sid=&q=2849411), where he wrote:
> I assume it's archaic. No hits in the ngrams or Aozora.
> Do we actually need this? I feel that archaic/obsolete terms should have to meet more than just the "is it already in one or more dictionaries?" criteria before they're considered for inclusion. Even daijr and daijs don't have this. Maybe a discussion for the mailing list.

Certainly worth discussing to try and achieve a general approach to these things.

I think it's OK to include terms if they are in one or more reputable 国語s, but if they are rare and/or not in current use (as is the case here) they should be tagged with [arch]. [obsc], etc. to flag that they shouldn't be used freely.

An advantage of including them when they're proposed is that it avoids going through a (re)evaluation every time someone comes across them in 広辞苑, 日本国語大辞典, etc. and suggests them for an entry. I realise this is a bit of a cop-out but I think we can assume the lexicographers at Iwanami, etc. have done their work.

**Comment by Marcusjmdict** [comment]
I don't think it's much of an issue, unless we were suddenly flooded with such submissions.

**Comment by JMdictProject** [comment]
I have added a sentence to https://www.edrdg.org/wiki/index.php/Editorial_policy#Is_it_worth_including.3F - "If a term is only in one or more 国語辞典 and has a low n-gram count and/or few WWW hits it should be tagged as "arch" or "obsc" as appropriate to signal that it is not in common use."

That will probably do it.

**Comment by JMdictProject** [comment]
Can probably close this now.
