### ISSUE TITLE
Regularizing hyphen characters

### ISSUE THREAD

**Issue by JMdictProject** [JMdictProject/JMdictIssues#34]
The Unicode code-set has nine different characters that can be used as hyphens. Fortunately, only four are currently being used in JMdict, however there are some inconsistencies in their use. We need to specify which characters are being used in particular contexts, in order to prevent round-trip conversion problems and to enable consistency in searching.

The characters are:

o -   (ASCII:0x2d)    U+2d    Hyphen (Note 3)
o ー  (JIS:0x213c)    U+30fc  Long vowel symbol used mainly with katakana
o ―   (JIS:0x213d)    U+2015  JIS/Unicode "HORIZONTAL BAR"  (X) (Note 3)
o ‐   (JIS:0x213e)    U+2010  JIS/Unicode "HYPHEN (Note 2) (Note 3)
o −   (JIS:0x215d)    U+2212  JIS/Unicode "MINUS SIGN"    (Note 1) (Note 3)
o －  (JIS:none)  U+FF0D  Unicode "FULLWIDTH HYPHEN-MINUS"    (X) (Note 3)
o ‑   (JIS:none)  U+2011  Unicode "non-breaking hyphen)   (X)
o ‒   (JIS:none)  U+2012  Unicode "figure dash"   (X)
o –   (JIS:none)  U+2013  Unicode "en dash" (X)
(X) Not used in JMdict
Note 1: Currently used in the kanji part of several entries, e.g. 1059440/ＣＤ−ＲＯＭ
Note 2: Currently  used in the kanji part of 2827637/Ｗｉ‐Ｆｉ
Note 3: Many browsers display these characters as the same, and will match them when doing a "find in page". They are treated differently, however, when entered in a text box, etc.

I propose the following rules for the use of these characters:
A. Only the regular "ASCII" hyphen is to be used in the glosses, notes, etc. in entries.
B. Where there are hyphens in the kanji part of entries, the ASCII hyphen will be used. While some Japanese texts use other characters, many if not most use the short hyphen, as do most references. This largely applies to terms such as "CD-ROM.
C. The long vowel character is only to be used in the context of terms in katakana.
D. The minus character is only to be used in algebraic or arithmetic contexts.

None of the other six characters is to be used.

Any discussion?

Jim

**Comment by polm** [comment]
That all sounds perfectly reasonable.

**Comment by JMdictProject** [comment]
I will close this now, and insert an appropriate section in the Editorial Policy.
