### ISSUE TITLE
Brazilian Japanese (コロニア語) terms?

### ISSUE THREAD

**Issue by jimmubreen** [JMdictProject/JMdictIssues#4]
The question has arisen in a couple of entries, most recently キッベ/kibbeh, whether the form or usage of Japanese in Brazil (コロニア語) should be recorded, and whether there should be a Brazilian dialect tag. A fair question; Brazil's population of Japan-born/descended people is the largest outside Japan itself (1.4M), and while it's not the first language form most of them, there's a thriving use of the language, with newspapers in it, etc.
(I don't have a problem with recording such terms.)

**Comment by nicolasmaia** [comment]
I think it's a good idea to have a specific tag for this dialect.

**Comment by Marcusjmdict** [comment]
I'm in favor too.

**Comment by JMdictProject** [comment]
I propose to add [bra] tag to the dialects for this purpose.

**Comment by JMdictProject** [comment]
This has now been added.
