### ISSUE TITLE
Changing misc [m-sl] to [manga]field 

### ISSUE THREAD

**Issue by Marcusjmdict** [JMdictProject/JMdictIssues#41]
I've always thought our [m-sl] manga slang tag is a little weird. I'm not sure "manga slang" is a real thing. Could we change it to [manga] and define it as field tag covering things relating to manga and anime?  (but I wouldn't want to include technical animation terms like "inbetweening", so "manga" and "anime" in the English sense)

**Comment by JMdictProject** [comment]
Yes, a lot of it is more about terms used in and about manga/anime than actual slang. A tag that indicated that, such as [m-anim] or something like that would probably be better. Suggestions welcome.  Once we have a suitable version I'll put it on the list of changes.

There are only 25 entries with this tag. They should be reviewed.

**Comment by robinjmdict** [comment]
I agree with the proposed change. I think "manga slang" is a thing but we don't need a dedicated tag for it.

Should manga/anime terms that are also slang (e.g. ダンデレ, 乳袋) be tagged as [manga] or [manga,slang]? If we're not using [manga] for technical terms, are all [manga] terms slang by default?

**Comment by Marcusjmdict** [comment]
I would think that entries tagged with the new tag wouldn't necessarily be slang or even col - for example, 4コマ is neither (though maybe it could be considered a "technical term"...?). So in the case of 乳袋 I suggest it should be tagged [manga,sl].

**Comment by JMdictProject** [comment]
I have added this to the issues related to misc and field tags. Further discussion there please.
