### ISSUE TITLE
Prefecture entries

### ISSUE THREAD

**Issue by Marcusjmdict** [JMdictProject/JMdictIssues#43]
How should we style the glosses for entries for prefectures like 和歌山県, 大阪府, 東京都? There's a considerable discrepancy among the entries in jmdict.

兵庫県: "Hyogo prefecture (Kinki area) (Hyougo)"
佐賀県: "Saga prefecture (Kyushu)"
富山県: "Toyama prefecture (Hokuriku area)"
東京都: "Tokyo Metropolis (prefecture); Tokyo metropolitan area"
大阪府: "Osaka prefecture"
京都府: "Kyoto Prefecture"

I suggest we style all of them simply as 
兵庫県: "Hyogo Prefecture"

(though 東京都 can maybe include the "(prefecture)" bit and/or some other explanation the others don't as it's a unique case)

I think we can remove the "area" info from the entries that have it. We don't include this info in the entries with the 県, 府, 都 suffixes. I think we might as well capitalize "Prefecture". Wikipedia uses uppercase P, though Britannica uses lowercase. Search results for various prefecture names on site:go.jp, site:gov, site:ac.uk are overwhelmingly uppercase. site:jiji.com and site:japantimes.com seems to 100% uppercase. site:nytimes.com is mostly uppercase. site:guardian.co.uk is mostly lowercase. site:washingpost.com and site:apnews.com are very mixed.

**Comment by robinjmdict** [comment]
> I suggest we style all of them simply as
> 兵庫県: "Hyogo Prefecture"

Sounds good to me.

> I think we can remove the "area" info from the entries that have it.

I agree.

**Comment by Marcusjmdict** [comment]
There were less discrepancy among these entries than I had thought, actually, outside of the Kansai ones I was checking before I posted this. I ended up just capitalizing the "P" in Prefecture and adding the region info to the two or three regions that didn't have it (except Okinawa, which is its own region). I would have felt bad about removing all that information.

**Comment by JMdictProject** [comment]
I think the "Hyogo Prefecture" style is fine. 

If we agree on that, I suggest editors simple make the changes and approve them.

BTW, we want Hyogo and not Hyōgo?

**Comment by JMdictProject** [comment]
I think this can be closed.
