### ISSUE TITLE
ritsuryo period handling

### ISSUE THREAD

**Issue by JMdictProject** [JMdictProject/JMdictIssues#45]
Two related issues here:
- Marcus has suggested that all the senses covering terms related to the ritsuryo period be marked [hist], and if so can it be done as a bulk update. I think they can, but it will be a bit fiddly as about 1/3 of the ~160 entries involved have the ritsuryo sense in the non-initial position. I'll leave the issue open until I can get to it.
- Opencooper asked whether it should be ritsuryō rather than ritsuryo. Quite possibly. At present only 6 entries use the ritsuryō form.

**Comment by Marcusjmdict** [comment]
Policy: Terms that are not regularly used in English should use macrons, e.g. "man'yōgana".

So "ritsuryō" instead of "ritsuryo" sounds about right to me.

**Comment by JMdictProject** [comment]
I'm about halfway through doing the ritsuryo to ritsuryō conversion. The bulk edit generation is a bit more complicated for multi-sense entries.

**Comment by JMdictProject** [comment]
These have all been done. (I have a more sophisticated generator for these sorts of updates.)
