### ISSUE TITLE
Marking transitivity for Sino-Japanese verbs ([vs] verbs)

### ISSUE THREAD

**Issue by Marcusjmdict** [JMdictProject/JMdictIssues#48]
https://ir.library.osaka-u.ac.jp/repo/ouka/all/71882/ffle_02_067.pdf
On Presenting Word Class Information : in Japanese Learners’ Bilingual Dictionaries

in the above 2019 paper which compares jmdict (jisho.org) with several paper dictionaries, the authors note: 

p.73
> Another issue with Sino-Japanese -suru verbs is the transitivity of these verbs. Some of the -suru
> verbs such as hassei-suru ‘to occur’ are intransitive, some such as satsugai-suru ‘to kill’ are transitive,
> and others such as kakudai-suru ‘to expand’ can be used both as transitive and intransitive verbs. An
> ideal learners’ dictionary, in addition to determining which Sino-Japanese nouns can be used as -suru
> verbs, will also provide the users with information about the transitivity of these verbs.

p.76-77
> The second question regarding Sino-Japanese verbs was if the dictionaries indicate their
> transitivity or not. Surprisingly, only two of the dictionaries had the transitivity labels for Sino-
> Japanese verbs, and one dictionary, (Japanese-Portuguese dictionary), had the transitivity labels for
> only some of the Sino-Japanese verbs. Finally, the two dictionaries that mark the transitivity of SinoJapanese verbs also indicate the dual behavior of the Sino-Japanese verbs that can be used both as
> transitive and intransitive verbs. 

The Sino-Japanese "verbs" they checked are included in an appendix:

> genryō ‘weight loss’
> kaihō ‘opening’
> kaitō ‘completing’
> kakudai ‘expansion’
> kanbi ‘equipped’
> keizoku ‘continuation’
> shukushō ‘shrinking’
> shōshitsu ‘loss’
> tenkai ‘development’
> tenkai ‘rotation’

Should we start marking [vs] "-suru verbs" with [vt]/[vi]?

**Comment by birtles** [comment]
> Should we start marking [vs] "-suru verbs" with [vt]/[vi]?

I think that would be incredibly helpful.

**Comment by robinjmdict** [comment]
I agree it could be helpful but if we're to do this, I think we'd need to introduce [vs-i] and [vs-t] tags. A noun can't be transitive or intransitive so putting [vi]/[vt] on a noun entry would be incorrect, in my view. 

Here's how Meikyo does it:

transitive:〘名・他サ変〙intransitive:〘名・自サ変〙 both:〘名・自他サ変〙　

The transitivity is incorporated into the サ変 PoS.

**Comment by wareya** [comment]
Would that be added in addition to the [vs] tag or would it replace it (for words with known transitivity)?

**Comment by ReneMalenfant** [comment]
I'm fine with [vi]/[vt] on a noun, as long as it's [n,vs,vi], for example.  That would be consistent with how we list vi/vt on other entries.  Just [n,vi] wouldn't work for me.

I think Meikyo is maybe being misinterpreted here?  On verbs that we label [v5k,vi], for example, Meikyo has them as 自五.  But we don't have a [v5k-i] PoS or a [v5i] tag.  So it seems to me like [n,vs,vi] would be more consistent with our current style of [v5k,vi] (and would avoid the need for another PoS).

**Comment by robinjmdict** [comment]
> On verbs that we label [v5k,vi], for example, Meikyo has them as 自五. But we don't have a [v5k-i] PoS or a [v5i] tag.

That's true, but I still feel it's wrong to tag a noun as an "intransitive/transitive verb". Verbs always have transitivity so it's fine to keep the POS and transitivity tags separate. For nouns that can take する, [vi]/[vt] only applies to する usage.

**Comment by JMdictProject** [comment]
I prefer just using vi/vt to introducing new tags. I think it will be quite clear that they apply to the XXする and not to XX the noun.

**Comment by Marcusjmdict** [comment]
I think it can be viewed as a downstream presentation issue. It shouldn't be hard for apps/sites to identify these entries and lump these entry tags together somehow if they would want to (as "n, vs (vi)" for example). I agree with Rene that as long as the vs comes first, there shouldn't be an issue, and with Jim that it should be obvious that vi/vt only applies to the "vs" bit.

**Comment by robinjmdict** [comment]
> I think it can be viewed as a downstream presentation issue. It shouldn't be hard for apps/sites to identify these entries and for example lump these entry tags together somehow if they would want to (as "n, vs (vi)" for example). 

Fair point. I yield.

**Comment by JMdictProject** [comment]
OK. I think this can be closed. I don't think the Editorial page needs to be changed.

**Comment by Marcusjmdict** [comment]
I'm going through our ichi1/spec1 [vs] entries, trying to mark all that are vs in meikyo. Marked around 200-250 today, will try and get back to it later. (edit: did another set of 200+)
 I'm on this page of the search results right now:
https://www.edrdg.org/jmdictdb/cgi-bin/srchres.py?next=Next+page&pt=2077&p0=400&p1=500&soj=%7B%22idnum%22%3A+null%2C+%22idtyp%22%3A+%22seq%22%2C+%22pos%22%3A+%5B%2246%22%5D%2C+%22misc%22%3A+%5B%5D%2C+%22fld%22%3A+%5B%5D%2C+%22dial%22%3A+%5B%5D%2C+%22rinf%22%3A+%5B%5D%2C+%22kinf%22%3A+%5B%5D%2C+%22freq%22%3A+%5B%22ichi1%22%2C+%22spec1%22%5D%2C+%22grp%22%3A+%5B%5D%2C+%22src%22%3A+%5B%221%22%5D%2C+%22stat%22%3A+%5B%222%22%5D%2C+%22unap%22%3A+%5B%22appr%22%2C+%22unappr%22%5D%2C+%22nfval%22%3A+null%2C+%22nfcmp%22%3A+null%2C+%22snote%22%3A+%5B%22%22%2C+0%5D%2C+%22ts%22%3A+%5Bnull%2C+null%5D%2C+%22smtr%22%3A+%5B%22%22%2C+0%5D%2C+%22cmts%22%3A+%5B%22%22%2C+0%5D%2C+%22refs%22%3A+%5B%22%22%2C+0%5D%2C+%22mt%22%3A+%220%22%7D&svc=jmdict

**Comment by JMdictProject** [comment]
Please self-approve as much as possible. The backlog is very large.

**Comment by JMdictProject** [comment]
I've been asked if vi/vt tags can be added in bulk - the short answer is all I need is the entry number, the sense number and whether it's vi or vt or both.

I could also put together a scheme for checking the n-grams counts, e.g. something like this:
冷蔵 | 1009709
冷蔵する | 4353
冷蔵して | 8764
冷蔵した | 2725
冷蔵します | 707
に冷蔵する | 267
に冷蔵して | 394
に冷蔵した | 135
に冷蔵します | 30
を冷蔵する | 383
を冷蔵して | 908
を冷蔵した | 133
が冷蔵する | 20
が冷蔵して | 47
が冷蔵した | 47

It doesn't look like the case for 冷蔵 being vs is strong.

**Comment by Marcusjmdict** [comment]
If somebody could automatically extract the [vt, vi] tags from Meikyo (or another source), it might be worthwhile. Otherwise I think it would only be marginally more efficient, at best.

**Comment by robinjmdict** [comment]
> If somebody could automatically extract the [vt, vi] tags from Meikyo (or another source), it might be worthwhile.

This is what I was thinking. It was me who asked Jim about automating the process. I found a tool that exports EPWING data to a UTF-8 encoded JSON file. I just tried it on Meikyo and it worked.

If I have some time in the next few days, I'll write a script that extracts all single-sense vs nouns, sorted by transitivity. 

I'm restricting it to single-sense entries because entries with multiple senses in Meikyo don't necessarily align perfectly with the corresponding entries in JMdict.

**Comment by JMdictProject** [comment]
Robin slipped me a copy of the Meikyo EB and  I found a Linux utility that ripped the contents into a text file (via JSON).
There are just on 8k entries with 〘名・他サ変〙,〘名・自サ変〙 or 〘名・自他サ変〙 as tags. E.g.
あい‐いん【愛飲】
〘名・他サ変〙
特定の飲料をいつも好んで飲むこと。
「吟醸酒ぎんじょうしゅを━する」

About 6.7k have only one sense.

It shouldn't be too hard to align them with JMdict entries. 
I meant to add that the bulk-update script command lines to add "vt" to the above entry would be:

seq 1150530
add pos vt

**Comment by Marcusjmdict** [comment]
That sounds great. Some of the JMDict equivalents of those 6.7k entries will probably have multiple senses but getting the rest out of the way would be great. If you make a separate list for the remaining 1.3k+ entries with multiple senses, I could go through those manually. BTW out of those entries I've added this data for, I went with [vt,vi] (i.e. in that order) for those that are 自他 in Meikyo just because "transitivity and intransitivity" makes more sense in English than the opposite. I didn't try and figure out which one was more common and I think we might as well not but just standardize it as [vt,vi] across the board.

**Comment by JMdictProject** [comment]
I have put the multi-sense ones at http://www.edrdg.org/~jwb/files/meikyo_text_vs2.html  Format is a bit crude.

**Comment by Marcusjmdict** [comment]
I noticed btw wadoku also has vt/vi info on at least some of its vs entries, for example 悪変
https://www.wadoku.de/entry/view/9969485

> (N., mit suru intrans. V.)

**Comment by Marcusjmdict** [comment]
I'm going through the multi-sense list little by little. I guess this can be closed for now.

**Comment by Marcusjmdict** [comment]
> I have put the multi-sense ones at http://www.edrdg.org/~jwb/files/meikyo_text_vs2.html Format is a bit crude.

Entries that have only 1 sense in Meikyo but multiple ones in Jmdict have been skipped over and aren't on the multi-sense list (死亡 for example). Might it be possible to put together a separate list for them?

**Comment by JMdictProject** [comment]
See http://www.edrdg.org/~jwb/files/meikyo_JMD_more.html   It's a bit crude but should help, There's almost 500 of them.
