### ISSUE TITLE
JMnedict timestamped meta-entry

### ISSUE THREAD

**Issue by Marcusjmdict** [JMdictProject/JMdictIssues#49]
We implemented a time-stamped meta entry on the suggestion of Opencooper in 2019, as
"ＪＭｄｉｃｔ 【ジェエムディクト】 (n) Japanese-Multilingual Dictionary Project -
Creation Date: yyyy-mm-dd"

Could we add a similar one to JMnedict too?

**Comment by JMdictProject** [comment]
Should be able to do that. It will be next week before I can get to it.

**Comment by JMdictProject** [comment]
OK. That's in - first edition out tomorrow.
