### ISSUE TITLE
Scope for field tags such as [sports] and [food]

### ISSUE THREAD

**Issue by jimmubreen** [JMdictProject/JMdictIssues#5]
A contributor (Guillem Palau-Salvà) is currently putting "sports" and "food" tags on a lot of entries, one of which is the ゴルフ entry. I have mostly been waving them through, but for that one I noted: "Don't usually have it on the names of sports."  Robin Scott, removed it, saying: "For consistency's sake, I don't think we should start using it for names of sports."  

I'd like to make sure we're on the same page here, and there probably should be something in the editorial guidelines/policy about the scope for these tags. When I first put them in years ago I had in mind that it might be good to use them so that if one extracted all the entries tagged "sports" there'd be a usable sporting terms glossary. On those grounds maybe entries like ゴルフ and テニス should get tagged. OTOH the major references don't usually tag the names of sports; only the terms used within sports. I've gone off the idea of extracting glossaries, so I'm comfortable with not having ゴルフ, テニス, ラグビー, etc. tagged.

The same goes for other fields such as food. Should ピッツァ, カレー, etc. be tagged? After all we don't balk at "symphony" and "concerto" being tagged as [music].

What are others' views on this?

**Comment by JMdictProject** [comment]
After ~15 months this issue may as well be closed. If anyone wants to express a view, it can be reopened.
