### ISSUE TITLE
[ling] and [gramm] usage.

### ISSUE THREAD

**Issue by JMdictProject** [JMdictProject/JMdictIssues#51]
We have had the [ling] (linguistics) field tag for many years, and now have 760 entries marked with it. More recently we added the [gramm] (grammar) tag, and now have 30 entries tagged. There may be a bit of confusion about which to use, which is understandable as grammar is really part of the broad field of linguistics.

From what I can see, many of the existing  [ling]  entries should be retagged [gramm]. GG5 uses the 【言】 tag for linguistic terms and 【文法】 fro grammatical ones. The [gramm] tag should be used for entries dealing directly with grammatical issues - POS, tense, case, etc. General language matters should get [ling].

Examples where we could change tag include 三人称, 使役動詞, 指示語, ...

**Comment by JMdictProject** [comment]
I just did a quick scan of my text copy of the GG5 contents. 346 entries/subentries are marked 【文法】 and 136 are marked 【言】, It is probably appropriate to consider a bulk conversion.

**Comment by robinjmdict** [comment]
> It is probably appropriate to consider a bulk conversion

Sounds good to me. We'd have to restrict it to single-sense entries, as we did with the vt/vi tagging. We can go through the rest by hand.

I'm surprised we have that many linguistics/grammar terms.

**Comment by JMdictProject** [comment]
OK, about 200 entries have had their tags changed from "ling' to "gramm". I'll close this now.
