### ISSUE TITLE
[euph] misc tag?

### ISSUE THREAD

**Issue by Marcusjmdict** [JMdictProject/JMdictIssues#53]
We have a lote of notes mentioning definitions are euphemisms or used euphemistically, e.g. 秘所https://www.edrdg.org/jmdictdb/cgi-bin/entr.py?svc=jmdict&sid=&e=2088816

Maybe it's about time we bit the bullet and made it a tag?

Another candidate for the tag:  https://www.edrdg.org/jmdictdb/cgi-bin/entr.py?svc=jmdict&sid=&e=1985274

**Comment by robinjmdict** [comment]
I think that's a good idea. We have 13 entries with notes containing "euphemism", "euphemistic" or "euph."

Should the full name of the tag be "euphemism" or "euphemistic"? Oxford and Wiktionary use "euphemistic".

**Comment by JMdictProject** [comment]
OK. I've added it to the list and I'll close this one.
