### ISSUE TITLE
Additional and changed misc tags

### ISSUE THREAD

**Issue by JMdictProject** [JMdictProject/JMdictIssues#54]
This is a consolidated issue from several others.
- from issue #53, a "euph" tag.
- replacement of "m-sl" with "manga" (This can be done by changing the database labels. The 28 existing "m-sl" entries would get the new tag.

**Comment by JMdictProject** [comment]
Ah. I see that we'd actually drop the "m-sl" and add the "manga" field tag.  Different process. Can be done with a bulk update.

**Comment by Marcusjmdict** [comment]
Does discussion of jmnedict tags go here?

How about [ship]? See ダイヤモンドプリンセス
[obj] is a little awkward here and individual ships are usually named entitites
https://www.edrdg.org/jmdictdb/cgi-bin/entr.py?q=5743536&svc=jmdict&sid=

**Comment by JMdictProject** [comment]
Noting that a "dentistry" tag would be useful. GG5 uses 【歯科】 and sometimes just 【歯】.

**Comment by Marcusjmdict** [comment]
Should we maybe change [hanaf] for hanafuda to [playingcards]? There's quite a bit of overlap with hanafuda, kabufuda and other mekuri karuta games and concepts. But restricting it just to [karuta] would also be a little complicated as there's a fair amount of overlap with the modern Western deck too, most if not all kabu games are actually most commonly played with Western decks today.

**Comment by JMdictProject** [comment]
Now being handled in #68
