### ISSUE TITLE
Broken links on edrdg.org

### ISSUE THREAD

**Issue by Marcusjmdict** [JMdictProject/JMdictIssues#56]
http://www.edrdg.org/jmdict/edict_doc.html#IREF01

The links to the current downloads of the dictionary files (http://ftp.monash.edu/pub/nihongo/ ...) all seem to be broken. They should probably be replaced with the ftp.edrdg.org links here?
http://www.edrdg.org/wiki/index.php/JMdict-EDICT_Dictionary_Project#CURRENT_VERSION_.26_DOWNLOAD

**Comment by NaincyKumariKnoldus** [comment]
hey @Marcusjmdict Can I work on it?

**Comment by JMdictProject** [comment]
Old page. Did you see the text in red at the top?

**Comment by Marcusjmdict** [comment]
I missed it (which I think means it's easy to miss). It's the first page that appears for me when googling "jmdict download" and the up-to-date one doesn't even show on the first page of results. Is there any reason to keep an out-of-date page around? Wouldn't it be better to just make it a redirect to the updated page?

**Comment by JMdictProject** [comment]
OK. That page has been replaced with a redirection.
