### ISSUE TITLE
Revive the [geom] field tag?

### ISSUE THREAD

**Issue by JMdictProject** [JMdictProject/JMdictIssues#60]
Just over 5 years ago we sort-of withdrew the [geom] field tag in favour of just using [math]. See: http://www.edrdg.org/jmdict_edict_list/2016/msg00043.html  16 entries were changed. Since then it has been used in 5 entries and its revival has been suggested (see the 焦点 entry.) We have also added and begun using [stat].

So, do we bring it back? Do we add [alg] as well?

**Comment by robinjmdict** [comment]
Dictionaries like Oxfam and Collins have a geometry field tag, which is what prompted me to add [geom] to those entries (not knowing that it had been retired). I think there are enough geometry-related terms that it's worth having a separate tag for them. I think algebra is too broad an area of mathematics for a tag to be useful.

**Comment by JMdictProject** [comment]
I took my eye off this one. I guess we should switch some or all of the ones Mislav changed back to "geom".
They can be found via the Advanced Search page using a date range starting with 2016/08/19 for a week or so, and selecting "math" entries.

**Comment by JMdictProject** [comment]
OK, I;ve gone through them and changed a few. I think the issue can be closed.
