### ISSUE TITLE
Rename obsolete tag from "obs" to disambiguate from "obsc"

### ISSUE THREAD

**Issue by opencooper** [JMdictProject/JMdictIssues#64]
Currently, the tag for an obsolete term is "obs", and for an obscure term, "obsc". I think the fact that "obs" could stand for either leads to unnecessary confusion.[0] A small change to lessen the potential for confusion would be to add an extra letter to "obs", e.g. "obsl".

[0]: [A recent example](https://www.edrdg.org/jmdictdb/cgi-bin/entr.py?svc=jmdict&sid=&q=1905690.1), but I've also wondered in the past if an editor meant to apply the other tag.

**Comment by robinjmdict** [comment]
I'd be in favour of reviving the "rare" tag (six entries still have it, funnily enough) and using that instead of "obsc". It's impossible to confuse with "obs" and I prefer "rare" to "obscure" as an adjective for describing uncommon terms. It's also what [Oxford uses](https://www.lexico.com/definition/gabion_knife).

**Comment by Marcusjmdict** [comment]
Sounds good to me, though if we go by intuitive meanings of the words "rare" would obviously apply to a whole lot more words than "obscure" does. Not necessarily a bad thing, though.

**Comment by JMdictProject** [comment]
I quite forget why "rare" was deprecated or fell into disuse. I'd hate to have to explain the precise difference as applied to entries.
I think changing "obsc" to "rare" is not a bad thing. It's actually a relatively simple thing to do as the actual tag in the DB is numeric and the text/number pairs are in a table. I may as well go and change the existing 6 "rare" entries to "obsc" (pro tem) as preparation. There may be some other tag changes.

**Comment by JMdictProject** [comment]
Now being handled in #68
