### ISSUE TITLE
〜省 entries: Ministry and Department names

### ISSUE THREAD

**Issue by jimmubreen** [JMdictProject/JMdictIssues#7]
The recent submission of an entry for 観光省 has highlighted that we possibly need a more consistent way of handling the names of ministries and departments.
- some, e.g. 農林水産省, are uniquely Japanese. We don't indicate that; perhaps we should.
- some are names that are used in Japan and also elsewhere, e.g. 財務省, which is the Ministry of Finance (in Japan), the Department of the Treasury in the US and in Australia, and is probably used for equivalent bodies elsewhere. (法務省 is Ministry of Justice in Japan, and is used for the Attorney-General’s Department in Australia).
- others, such as 観光省 (Ministry of Tourism, Department of Tourism, etc.) is not used in Japan itself, but can be found in Japanese documents referring to other countries.

Some questions that should be addressed include:
- do we attempt to indicate some of the countries where particular names apply?
- in particular, do we indicate which names apply to Japanese ministries, e.g. put "(Jpn)" or something similar in the glosses for 農林水産省, etc.?
- do we divide the Japanese and other names into different senses? (GG5 does this for the 財務省 entry.)
- for names like 観光省 (presumably "Ministry of Tourism", "Department of Tourism") do we attempt to indicate that it is generic, list a few countries (e.g. Brazil, India, New Zealand, etc.), or just leave it blank

**Comment by Marcusjmdict** [comment]
I think "Ministry of Tourism (Brazil, India, New Zealand, etc.); Department of Tourism (South Africa, Philippines, etc.)" as 観光省 is glossed now is rather unsightly. Can't we just call it "Ministry of Tourism" and leave the rest to the imagination? For other entries, I suggest leading with the official Japanese name and listing other similar names, when needed, without comment, e.g. in the case of 観光省, "Ministry of Tourism; Department of Tourism"

**Comment by robinjmdict** [comment]
I agree with Marcus. Keep it simple.

**Comment by JMdictProject** [comment]
I think this can close.
