### ISSUE TITLE
More する-verb transitivity tags

### ISSUE THREAD

**Issue by stephenmk** [JMdictProject/JMdictIssues#70]
I found 120 more する-verb entries which contain only one sense in JMdict (or rather, only one sense containing English-language glosses) and one sense in the second edition of 明鏡国語辞典, but were not updated as expected by last year's automated process. Do we want to update these in bulk or individually through the JMdictDB web interface?

https://gist.github.com/stephenmk/76dbff7ba77589db8a2513e7a043d30a

The above entries are already tagged as [vs], [vs-i], [vs-s], or [vz] in JMdict. I also found 221 entries in JMdict which do not have any variety of [vs] tag but are marked as サ変 in Meikyo. Again, I believe these should have one-to-one sense correspondence. For example, 開城 (かいじょう) has two separate entries in JMdict, each with only one sense, but I accounted for these sorts of situations.

https://gist.github.com/stephenmk/f46cabb99654609b4de69b6a764705b3

**Comment by JMdictProject** [comment]
I should be able to do those using the bulk updater. It will probably be next week before I get to it.

**Comment by JMdictProject** [comment]
I have set up the first batch of 120 and tested it. I'll run it shortly. The updater defaults to adding the tag at the end, but in some cases that's not optimal. I'd have to do hand-springs to handle them automatically, so I think I'll just run it and fix up the outliers by hand.

**Comment by JMdictProject** [comment]
OK, those are all done. I tweaked the POS order by hand in some of the first batch.
I'll close the issue now.
