### ISSUE TITLE
Potential yojijukugo in JMdict without the [yoji] tag

### ISSUE THREAD

**Issue by stephenmk** [JMdictProject/JMdictIssues#74]
I found about 200 entries in JMdict without the [yoji] tag which contain surface forms that may be found in other yoji dictionaries*. We may want to add [yoji] miscellaneous tags to some or all of these entries.

https://gist.github.com/stephenmk/c8df5b07d164c65d85ff46f1f30e6d8d

Note that I have not scraped all of jitenon, and there are likely many yoji in there that are not found in shinmeikai or gakken. I may get around to making a more complete list in the future.

\* The gakken and shinmeikai yoji dictionaries may be browsed at https://dictionary.goo.ne.jp/
\* jitenon: https://yoji.jitenon.jp/

**Comment by JMdictProject** [comment]
I have glanced at a sample from the list. Most seem quite plausible.
It would be simple to add a yoji tag to these using the bulk updater. In fact, perhaps the easiest thing would be to tag them all, then if people want to discuss individual cases that can happen via the edit process for the entries themselves.
Any comment from others on this?

**Comment by JMdictProject** [comment]
OK, they are done now. I'll close the issue for now.
