### ISSUE TITLE
Adding [hist] tag to historical provinces

### ISSUE THREAD

**Issue by robinjmdict** [JMdictProject/JMdictIssues#76]
A couple of years ago, 79 historical Japanese provinces were added to JMdict. Currently, only a few of them are tagged as "hist". Can we use the bulk updater to tag the rest?

[Here's a list](https://pastebin.com/ZrMDCJWu) of the relevant sequence numbers. I've excluded the entries where the province isn't the first sense. I'll amend these by hand.

**Comment by JMdictProject** [comment]
That should be fairly easy. I'll try and get to it soon. Thanks.

**Comment by JMdictProject** [comment]
OK. That batch has been done. I'll close this now.
