### ISSUE TITLE
jmnedict: tag for mythical or fictional entities

### ISSUE THREAD

**Issue by nicolasmaia** [JMdictProject/JMdictIssues#8]
Tags for things like these would be useful:

* https://www.edrdg.org/jmdictdb/cgi-bin/entr.py?svc=jmdict&sid=&e=1995876
* https://www.edrdg.org/jmdictdb/cgi-bin/entr.py?svc=jmdict&sid=&e=1998801

Perhaps under one tag, something like 'mythical or fictional entity'.

**Comment by jimmubreen** [comment]
Yes, something like that would be useful. There's an issue open covering possible additional jmnedict name types. I'll add this there.

**Comment by JMdictProject** [comment]
I'll close this as it's been added to #3.
