### ISSUE TITLE
A mountainous question

### ISSUE THREAD

**Issue by JMdictProject** [JMdictProject/JMdictIssues#80]
A recent submission to change the 高尾山 entry in JMnedict from "Mt Takao" to "Mount Takao" raises the general question of how we should be recording the names of mountains.

A quick grepping brings up the current counts:

Mt.  121
Mount  63
Mt 11

Should we standardize, or just let the entry be whatever the submitter wants?
If we do standardize, which form to we go for? I must say I don't like "Mt.", which is the AmE style (along with "Dr." and "Mr."). I prefer (and use) the BrE "Mt", "Dr", etc.

**Comment by robinjmdict** [comment]
I think we should stick to one form. "Mount" is probably the safest option.

**Comment by JMdictProject** [comment]
OK. Let's go with "Mount". Since there are about 130 entries to change, I'll set up a batch update. It may take a while, so I'll leave this issue open until it's done.

**Comment by JMdictProject** [comment]
OK. The batch update has been run.
