### ISSUE TITLE
Dynasties

### ISSUE THREAD

**Issue by JMdictProject** [JMdictProject/JMdictIssues#81]
There are about 200 entries in JMdict and JMnedict which contain the word "dynasty", usually referring to particular historical periods. Most of the entries are in the generally accepted style of "Tang dynasty", but a number use the styles "Tang Dynasty" and "Tang-dynasty".

Unless there are convincing objections, I plan to make them all follow the "Tang dynasty" style. I'll investigate using batch updates, and leave this issue open as a reminder.

**Comment by robinjmdict** [comment]
The "Tang-dynasty" style is for attributive use (i.e. when it comes before a noun). My initial thought was that this should be left unchanged but web results and [Google books ngrams](https://books.google.com/ngrams/graph?content=Tang-dynasty+China%2CTang+dynasty+China%2CTang-dynasty+poet%2CTang+dynasty+poet&year_start=1900&year_end=2019&corpus=26&smoothing=3&case_insensitive=true) show it's significantly more common not to include a hyphen. Compare with ["Meiji-era Japan"/"Meiji era Japan"](https://books.google.com/ngrams/graph?content=Meiji-era+Japan%2CMeiji+era+Japan&year_start=1900&year_end=2019&case_insensitive=on&corpus=26&smoothing=3).

I support using the lower-case "dynasty".

**Comment by Marcusjmdict** [comment]
Sounds good.

**Comment by JMdictProject** [comment]
Yes, I'd noticed the non-hyphen form was much more common.
I have run the bulk conversion. In a few cases such as "Southern Dynasty" I have left the capital,
I'll close this now.
