### ISSUE TITLE
Editorial page mnemonic for "RP" not present

### ISSUE THREAD

**Issue by briankrznarich** [JMdictProject/JMdictIssues#86]
Could an entry be added for "RP" to the list of sources on the Editorial Page wiki under "mnemonics for some of the popular sources".  

http://www.edrdg.org/wiki/index.php/Editorial_policy

I've seen a couple of references to RP, such as the two below, but I can't figure out what source this is.

https://www.edrdg.org/jmwsgi/entr.py?svc=jmdict&sid=&e=2198981
"RP, many Eijiro and GG5 examples."

https://www.edrdg.org/jmwsgi/entr.py?svc=jmdict&sid=&e=2221058
"RP: helmet liner : ヘルメットの裏当て; ..."

**Comment by stephenmk** [comment]
研究社「リーダーズ・プラス」, I think.

**Comment by JMdictProject** [comment]
Yes, that's the one. Sorry - I have now added it to the リーダーズ・プラス line  in https://www.edrdg.org/wiki/index.php/Editorial_policy#References

**Comment by robinjmdict** [comment]
Might be helpful to add these as well.

- meikyo: Meikyo Kokugo Jiten, [明鏡国語辞典](https://ja.wikipedia.org/wiki/%E6%98%8E%E9%8F%A1%E5%9B%BD%E8%AA%9E%E8%BE%9E%E5%85%B8) - small-sized 国語辞典
- sankoku: Sanseido Kokugo Jiten, [三省堂国語辞典](https://ja.wikipedia.org/wiki/%E4%B8%89%E7%9C%81%E5%A0%82%E5%9B%BD%E8%AA%9E%E8%BE%9E%E5%85%B8) - small-sized 国語辞典
- saito: Saito's Japanese-English Dictionary, [ＮＥＷ斎藤和英大辞典](https://www.nichigai.co.jp/cgi-bin/nga_search.cgi?KIND=BOOK&ID=A2934) - large Japanese-English dictionary published in 1928
- DDB: [Digital Dictionary of Buddhism](http://www.buddhism-dict.net/ddb/) - online Buddhism dictionary
- DBJG/DIJG/DAJG: A Dictionary of [Beginner](https://bookclub.japantimes.co.jp/en/book/b309630.html)/[Intermediate](https://bookclub.japantimes.co.jp/en/book/b309631.html)/[Advanced](https://bookclub.japantimes.co.jp/en/book/b309638.html) Japanese Grammar - grammar dictionaries by Seiichi Makino and Michio Tsutsui

**Comment by JMdictProject** [comment]
Good suggestions. I have added those. I'll leave this open for a bit,

**Comment by stephenmk** [comment]
* iwakoku: Iwanami Kokugo Jiten, [岩波国語辞典](https://ja.wikipedia.org/wiki/%E5%B2%A9%E6%B3%A2%E5%9B%BD%E8%AA%9E%E8%BE%9E%E5%85%B8) - small sized 国語辞典

If only to avoid confusion with other dictionaries published by Iwanami (like koj)

**Comment by JMdictProject** [comment]
Thanks. I've added that one.

**Comment by Marcusjmdict** [comment]
You could also add mk = meikyo
(though I might be the only one using that abbreviation)

**Comment by opencooper** [comment]
Some other suggestions:

* smk = shinmeikai 新明解国語辞典
* prog = progressive J-E プログレッシブ和英中辞典
* Preface "新和英中辞典: medium Kenkyusha JE dictionary" with "chuujiten"?
* Probably good to be aware for "カタカナ新語辞典 (Gakken)" that Gakken publishes other dictionaries
* Not exactly dictionaries, but we do sometimes refer to the tanaka/tatoeba sentences

**Comment by JMdictProject** [comment]
I did some fiddling with the References list, making the changes as suggested and also grouping them into Kokugo/JE/EJ/etc. sequences. I fixed a broken URL or two as well. Suggestions welcome.

**Comment by stephenmk** [comment]
The link for nikkoku appears to redirect to an unrelated site (http://www.nikkoku.net/ -> https://japanknowledge.com/tomonokai/).

Might be worth mentioning that the nikkoku entries on sites like kotobank.jp are pulled from the abridged 精選版 version rather than the full multi-volume version. It seems the full version was available online via yahoo some years ago, and some entry amendments reference it specifically.

**Comment by JMdictProject** [comment]
Thanks. I've dropped the link and added a note about the 精選版.
The References section is probably worth a page of its own.
