### ISSUE TITLE
Invalid format of <xref>: using centre-dot while doctype says it must not

### ISSUE THREAD

**Issue by scriptin** [JMdictProject/JMdictIssues#90]
Hello!

According to the JMdict's doctype:

```xml
<!ELEMENT xref (#PCDATA)*>
        <!-- This element is used to indicate a cross-reference to another
        entry with a similar or related meaning or sense. The content of
        this element is typically a keb or reb element in another entry. In some
        cases a keb will be followed by a reb and/or a sense number to provide
        a precise target for the cross-reference. Where this happens, a JIS
        "centre-dot" (0x2126) is placed between the components of the
        cross-reference. The target keb or reb must not contain a centre-dot.
```

Note the last sentence: "The target keb or reb must not contain a centre-dot."

In the latest release, I've just found several instances of this rule being broken:

```
$ grep '<xref>.*・.*・[^0-9]' JMdict.xml
<xref>ＯＨ・オー・エイチ</xref>
<xref>ＯＢ・オー・ビー・1</xref>
<xref>ＳＰ・エス・ピー・3</xref>
<xref>ＣＧＩ・シー・ジー・アイ・2</xref>
<xref>ＨＷＲ・エイチ・ダブリュー・アール</xref>
<xref>ＬＣＤ・エル・シー・ディー</xref>
<xref>ＣＭ・シー・エム・1</xref>
<xref>ＳＦ・エス・エフ</xref>
<xref>ユー・エス・ビー・1</xref>
<xref>ＤＫ・ディー・ケー・1</xref>
<xref>ＬＤＫ・エル・ディー・ケー</xref>
<xref>ＳＦ・エス・エフ</xref>
<xref>ＳＦＡ・エス・エフ・エー</xref>
```

Related to #88 and #89

**Comment by stephenmk** [comment]
I made note of this a [couple](https://www.edrdg.org/jmdictdb/cgi-bin/entr.py?svc=jmdict&sid=&q=2830086.1) of [times](https://www.edrdg.org/jmdictdb/cgi-bin/entr.py?svc=jmdict&sid=&q=1032960.1), but it seems some still managed to slip through.

Edit: Amendments now submitted for all the entries mentioned above. I also have [my own program for detecting irregularities in these \<xref\> elements](https://www.edrdg.org/jmdict_edict_list/2023/msg00003.html), and it only found [one other problem](https://www.edrdg.org/jmdictdb/cgi-bin/entr.py?svc=jmdict&sid=&q=2847153) in addition to those already noted.

**Comment by JMdictProject** [comment]
Thanks for pointing this out. I'd overlooked it totally, and I'd missed Stephen's comments.
The cases need to be tracked down and amended (in progress at the moment.) We also need to make sure that in future the xref is constructed to avoid including the nakaguro form.

The NG version of the JMdict XML will remove this problem.
(I'll leave the issue open for a bit to keep it visible.)

**Comment by JMdictProject** [comment]
Can close it now.
